var framedesinfo =
{
	frame001:       "Nome de utilizador :&nbsp;",
	frame002:       "Palavra-passe :&nbsp;",
	frame003:       "Iniciar sessão",
	frame004:       "Bem-vindo à página de Internet ONT da Huawei para configuração de rede.",
	frame006:       "Não é possível suportar versões do IE inferiores a 6.0.",
	frame007:       "Conta não pode ficar em branco.",
	frame008:       "A conta é inválida.",
	frame009:       "Palavra-passe não pode ficar em branco.",
	frame010:       "A palavra-passe é inválida.",
	frame011:       "Demasiadas tentativas, tente ",
	frame011a:      "Demasiadas tentativas, volte a tentar daqui a ",
	frame012:       " segundos mais tarde.",
	frame012a:      " segundo mais tarde.",
	frame012c:      " segundo",
	frame012d:      " segundos",
	frame013:       "Demasiadas tentativas.",
	frame013a:      "Demasiadas tentativas.",
	frame014:       "Nome de conta ou palavra-passe inválidos. Tente novamente.",
	frame015:       'Copyright © Huawei Technologies Co., Ltd 2022. Todos os direitos reservados.',
	frame015a:       'Copyright © 2022 Huawei Technologies Co., Ltd. Todos os direitos reservados.',
	frame016: 		'A versão do seu navegador está desatualizada (IE 6, IE 7 e IE 8 são incompatíveis). É preciso atualizar o navegador para a versão IE 9 ou superior. ',	

	mainpage001:    "Estado de ligação à rede:",
	mainpage002:    "normal",
	mainpage003:    "O estado da rede é anormal.",
	mainpage004:    "Diagnóstico rápido",
	mainpage005:    "Internet",
	mainpage006:    "Configuração de Wi-Fi",
	mainpage007:    "Verificar",
	mainpage008:    "Configurações rápidas",
	mainpage009:    "Terminar sessão",
	mainpage010:    "Dispositivos Wi-Fi",
	mainpage011:    "Dispositivos com fios",
	mainpage012:    "Telefones",
	mainpage013:    "Transferir APP",
	mainpage014:    "Diagnóstico rápido",
	mainpage015:    "REINICIAR",
	mainpage016:    "Nota: Actualização será interrompida e o dispositivo pode não iniciar com sucesso a próxima vez que mudar para outra página. É altamente recomendável pressionar cancelar e permanecer nesta página até a actualização estar concluída.",
	mainpage017:    "O sistema está a executar o diagnóstico rápido.",
	mainpage018:    "LAN Devices"
};
