var framedesinfo =
{
	frame001:       "Nombre de usuario :&nbsp;",
	frame002:       "Contraseña :&nbsp;",
	frame003:       "Iniciar sesión",
	frame004:       "Bienvenidos a la página web del ONT de Huawei para la configuración de la red.",
	frame004telmex:       "Bienvenido a la página web de Huawei que permite la configuración de la red.",
	frame006:       "No soportamos versiones de IE anteriores a 6.0.",
	frame007:       "La usuario es un campo obligatorio.",
	frame008:       "Cuenta no válida.",
	frame009:       "La contraseña es un campo requerido.",
	frame010:       "Contraseña no válida.",
	frame011:       "Ha intentado muchas veces. Vuelva a intentarlo dentro de ",
	frame012:       " segundos.",
	frame012a:      " segundo.",
	frame013:       "Ha intentado muchas veces.",
	frame013a:      "Ha intentado muchas veces.",
	frame014:       "La combinación de la usuario/contraseña es incorrecta. Favor de volver a intentarlo.",
	frame015:       'Copyright © Tecnologias Huawei Co., Ltd 2022. Todos los derechos reservados.',
	frame015a:       'Copyright © 2022 Tecnologias Huawei Co., Ltd. Todos los derechos reservados.',
	frame016: 		'La versión de su navegador está desactualizada (no se soportan IE 6, IE 7 ni IE 8). Debe actualizar el navegador con IE 9 o una versión posterior. ',
	frame0161: 		'¿Cómo obtener nombre de usuario y contraseña?',	
	frame017: 		'Buscar contraseña de inicio de sesión predeterminada.',
	frame018: 		'La contraseña predeterminada se encuentra en la placa de identificación del producto. ',
	frame019: 		'¿Olvidó la contraseña?',
	frame020: 		'Restablecer la contraseña de inicio de sesión predeterminada.',
	frame021: 		'Si modificó la contraseña de inicio de sesión y la olvidó, presione el botón de restablecimiento durante 10 s para restablecer la contraseña de inicio de sesión predeterminada que figura en la placa de identificación del producto.',	
	frame022: 		'Nota: Todos los ajustes establecidos se perderán una vez que se restablezcan los ajustes de fábrica del dispositivo.',

	mainpage001:    "Estado de la conexión de red:",
	mainpage002:    "normal",
	mainpage003:    "El estado de la red es anormal.",
	mainpage004:    "Diagnóstico con un clic",
	mainpage005:    "Internet",
	mainpage006:    "Configuración de Wi-Fi",
	mainpage007:    "Escanear",
	mainpage008:    "Configuración rápida",
	mainpage009:    "Cerrar sesión",
	mainpage010:    "Dispositivos Wi-Fi",
	mainpage011:    "Dispositivos cableados",
	mainpage012:    "Teléfonos",
	mainpage013:    "Descarga de APP",
	mainpage014:    "Diagnóstico con un clic",
	mainpage015:    "REINICIAR",
	mainpage016:    "Nota: Si decide cambiar de página, la actualización \nse interrumpirá y es posible que el dispositivo no arranque \nla próxima vez. Se recomienda presionar cancelar y permanecer en esta página hasta que se complete la actualización.",
	mainpage017:    "El sistema está realizando un diagnóstico con un solo clic. Si cierra esta página, se detendrá el diagnóstico. ¿Confirma cerrar la página?",
	mainpage018:    "LAN Devices"
};
