#include "hwfwtool/config.h"
#include "hwfwtool/utils.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

hw_error_t hw_config_generate(const hw_firmware_t *fw, const char *output_dir) {
    char *config_path = hw_path_join(output_dir, "config.ini");
    if (!config_path) return HW_ERR_MEMORY;

    FILE *f = fopen(config_path, "w");
    if (!f) {
        free(config_path);
        return HW_ERR_IO;
    }

    fprintf(f, "; Huawei Firmware Configuration\n");
    fprintf(f, "; Generated by " HWFWTOOL_NAME " v" HWFWTOOL_VERSION "\n");
    fprintf(f, "; Date: %llu\n", (unsigned long long)time(NULL));
    fprintf(f, "\n");

    fprintf(f, "[firmware]\n");
    fprintf(f, "magic = %s\n", fw->magic);
    fprintf(f, "version = %s\n", fw->firmware_version);
    fprintf(f, "product = %s\n", fw->product_info);
    fprintf(f, "carrier = %s\n", fw->carrier);
    fprintf(f, "region = %s\n", fw->region);
    fprintf(f, "country = %s\n", fw->country);
    fprintf(f, "file_size = %llu\n", (unsigned long long)fw->file_size);
    fprintf(f, "block_count = %u\n", fw->block_count);
    fprintf(f, "data_start = 0x%08llx\n", (unsigned long long)fw->data_start);
    fprintf(f, "data_end = 0x%08llx\n", (unsigned long long)fw->data_end);
    fprintf(f, "signed = %s\n", fw->is_signed ? "true" : "false");
    fprintf(f, "header_hash = 0x%08x\n", fw->header_hash);
    fprintf(f, "file_hash = 0x%08x\n", fw->file_hash);
    fprintf(f, "\n");

    for (uint32_t i = 0; i < fw->block_count; i++) {
        const hw_block_info_t *b = &fw->blocks[i];
        fprintf(f, "[block.%s]\n", b->name);
        fprintf(f, "index = %u\n", b->index);
        fprintf(f, "name = %s\n", b->name);
        fprintf(f, "flash_path = %s\n", b->flash_path);
        fprintf(f, "target = %s\n", hw_block_target_string(b->target));
        fprintf(f, "compression = %s\n", hw_compress_type_string(b->compression));
        fprintf(f, "comp_size = %u\n", b->comp_size);
        fprintf(f, "data_offset = 0x%08llx\n", (unsigned long long)b->data_offset);
        fprintf(f, "crc32 = 0x%08x\n", b->crc32);
        fprintf(f, "timestamp = 0x%08x\n", b->timestamp);
        if (b->has_version) {
            fprintf(f, "version = %s\n", b->version);
        }
        fprintf(f, "filename = raw/%s.bin\n", b->name);
        fprintf(f, "\n");
    }

    fprintf(f, "[trailer]\n");
    fprintf(f, "offset = 0x%08llx\n", (unsigned long long)fw->trailer_offset);
    fprintf(f, "size = %llu\n", (unsigned long long)fw->trailer_size);
    fprintf(f, "has_capability = %s\n", fw->has_capability ? "true" : "false");
    fprintf(f, "filename = trailer/trailer.bin\n");
    fprintf(f, "\n");

    fprintf(f, "[extract]\n");
    fprintf(f, "output_dir = %s\n", output_dir);
    fprintf(f, "raw_dir = raw\n");
    fprintf(f, "decompressed_dir = decompressed\n");
    fprintf(f, "trailer_dir = trailer\n");
    fprintf(f, "config_file = config.ini\n");
    fprintf(f, "manifest_file = manifest.xml\n");
    fprintf(f, "\n");

    fprintf(f, "[repack]\n");
    fprintf(f, "input_dir = %s\n", output_dir);
    fprintf(f, "output_file = repacked.bin\n");
    fprintf(f, "verify_crc = true\n");
    fprintf(f, "preserve_trailer = true\n");
    fprintf(f, "compress_blocks = true\n");
    fprintf(f, "\n");

    fclose(f);
    free(config_path);
    return HW_ERR_OK;
}

hw_error_t hw_config_load(hw_firmware_t *fw, const char *config_path) {
    (void)fw;
    FILE *f = fopen(config_path, "r");
    if (!f) {
        hw_log_error("Cannot open config: %s", config_path);
        return HW_ERR_IO;
    }

    char line[1024];
    while (fgets(line, sizeof(line), f)) {
        if (line[0] == ';' || line[0] == '#' || line[0] == '\n' || line[0] == '\r') continue;
    }

    fclose(f);
    return HW_ERR_OK;
}

hw_error_t hw_config_save_manifest(const hw_firmware_t *fw, const char *output_dir) {
    char *manifest_path = hw_path_join(output_dir, "manifest.xml");
    if (!manifest_path) return HW_ERR_MEMORY;

    FILE *f = fopen(manifest_path, "w");
    if (!f) {
        free(manifest_path);
        return HW_ERR_IO;
    }

    fprintf(f, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    fprintf(f, "<firmware>\n");
    fprintf(f, "  <info>\n");
    fprintf(f, "    <magic>%s</magic>\n", fw->magic);
    fprintf(f, "    <version>%s</version>\n", fw->firmware_version);
    fprintf(f, "    <product>%s</product>\n", fw->product_info);
    fprintf(f, "    <carrier>%s</carrier>\n", fw->carrier);
    fprintf(f, "    <region>%s</region>\n", fw->region);
    fprintf(f, "    <country>%s</country>\n", fw->country);
    fprintf(f, "    <file_size>%llu</file_size>\n", (unsigned long long)fw->file_size);
    fprintf(f, "    <signed>%s</signed>\n", fw->is_signed ? "true" : "false");
    fprintf(f, "  </info>\n");
    fprintf(f, "  <blocks count=\"%u\">\n", fw->block_count);

    for (uint32_t i = 0; i < fw->block_count; i++) {
        const hw_block_info_t *b = &fw->blocks[i];
        fprintf(f, "    <block>\n");
        fprintf(f, "      <index>%u</index>\n", b->index);
        fprintf(f, "      <name>%s</name>\n", b->name);
        fprintf(f, "      <flash_path>%s</flash_path>\n", b->flash_path);
        fprintf(f, "      <target>%s</target>\n", hw_block_target_string(b->target));
        fprintf(f, "      <compression>%s</compression>\n", hw_compress_type_string(b->compression));
        fprintf(f, "      <comp_size>%u</comp_size>\n", b->comp_size);
        fprintf(f, "      <data_offset>0x%08llx</data_offset>\n", (unsigned long long)b->data_offset);
        fprintf(f, "      <crc32>0x%08x</crc32>\n", b->crc32);
        fprintf(f, "      <timestamp>0x%08x</timestamp>\n", b->timestamp);
        if (b->has_version) {
            fprintf(f, "      <version>%s</version>\n", b->version);
        }
        fprintf(f, "    </block>\n");
    }

    fprintf(f, "  </blocks>\n");
    fprintf(f, "  <trailer>\n");
    fprintf(f, "    <offset>0x%08llx</offset>\n", (unsigned long long)fw->trailer_offset);
    fprintf(f, "    <size>%llu</size>\n", (unsigned long long)fw->trailer_size);
    fprintf(f, "    <has_capability>%s</has_capability>\n", fw->has_capability ? "true" : "false");
    fprintf(f, "  </trailer>\n");
    fprintf(f, "</firmware>\n");

    fclose(f);
    free(manifest_path);
    return HW_ERR_OK;
}

hw_error_t hw_config_save_block_list(const hw_firmware_t *fw, const char *output_dir) {
    char *list_path = hw_path_join(output_dir, "blocks.txt");
    if (!list_path) return HW_ERR_MEMORY;

    FILE *f = fopen(list_path, "w");
    if (!f) {
        free(list_path);
        return HW_ERR_IO;
    }

    fprintf(f, "# Huawei Firmware Block List\n");
    fprintf(f, "# Format: index name flash_path comp_size crc32 compression data_offset\n");
    fprintf(f, "#\n");

    for (uint32_t i = 0; i < fw->block_count; i++) {
        const hw_block_info_t *b = &fw->blocks[i];
        fprintf(f, "%u %s %s %u 0x%08x %s 0x%08llx\n",
                b->index, b->name, b->flash_path, b->comp_size, b->crc32,
                hw_compress_type_string(b->compression),
                (unsigned long long)b->data_offset);
    }

    fclose(f);
    free(list_path);
    return HW_ERR_OK;
}
