var XGManageDes = 
{
	s0100:    "Nesta página, é possível consultar informação sobre o cartão de dados em utilização, especificar uma rede e definir o código PIN para o cartão SIM.",	
	s0101:    "Configurar cartão de Internet 3G",
	s2101:    "Configuração da ligação à rede",
	s2102:    "Verifique a informação da versão do cartão de dados e verifique ou especifique a rede ligada a utilizar o cartão SIM.",
	s2103:    "Nome do cartão de dados:",
	s2104:    "Versão de software do cartão de dados:",
	s2105:    "Versão de hardware do cartão de dados:",
	s2106:    "Rede atual ligada:",
	s2107:    "Rede designada:",
	s2108:    "2G",
	s2109:    "3G",
	s210a:    "4G",
	s210b:    "AUTOMÁTICO",
	s210c:    "Configuração do código PIN",
	s210d:    "Verifique o estado do cartão SIM e configure um código PIN para o cartão SIM.",
	s210e:    "Estado do código PIN:",
	s210f:    "Ativar gestão do código PIN",
	s2111:    "Desativar código PIN",
	s2112:    "Alterar código PIN",
	s2113:    "Eliminar o código PIN guardado",
	s2114:    "Código PUK:",
	s2115:    "Código PIN:",
	s2116:    "Código PIN antigo:",
	s2117:    "Novo código PIN:",
	s2118:    "Confirmação do código PIN:",
	s2119:    "Tentativas disponíveis:",
	s211a:    "Insira um cartão SIM.",
	s211b:    "Não é possível ler o cartão SIM.",
	s211c:    "O cartão SIM foi bloqueado. Introduza o código PUK para restaurar o código PIN para desbloquear o cartão SIM.",
	s211d:    "Introduza o código PIN correto.",
	s211e:    "O código PIN foi desbloqueado. Agora pode utilizar o cartão SIM para navegar na Internet. Também poderá efetuar  as seguintes operações:",
	s211f:    "A gestão do número PIN foi desativada.",
	s2120:    "O código PIN deve consistir em 4 números. Introduza o código PIN correto.",
	s2121:    "O código PUK deve consistir em 8 números. Introduza o código PUK correto.",
	s2122:    "A confirmação do código PIN é diferente do novo código PIN.",
	s2123:    "Cartão SIM inválido.",
	s0905:    "O sistema está ocupado. Tente novamente mais tarde.",
	s0e08:    "Aplicar",
    s0e09:    "Cancelar"
};
 
﻿var AcsstatusLgeDes = 
{
	s0100:    "Gestão remota",
    s0301:    "Nesta página, pode ver o estado da ligação remota e o estado de fornecimento de serviços.",
    s0302:    "Estado de Relatório Não Solicitado:",
    s0303:    "Concluído com sucesso.",
    s0304:    "Não reportado",
    s0305:    "Sem resposta",
    s0306:    "Interrompido",
    s0307:    "Desconhecido",
    s0308:    "Estado da ligação ACS:",
    s0309:    "Ligação remota concluída com sucesso",
    s030a:    "Sem pedidos de ligações remotas",
    s030b:    "Ligação remota interrompida",
    s030c:    "Estado de Fornecimento de Serviços:",
    s030d:    "A receber configuração de serviços remoto",
    s030e:    "Configuração sucedida com sucesso",
    s030f:    "Falha de configuração",
    s0310:    "Configuração de serviços remotos não aplicada"
};
 
﻿var sectionsectionspeed_language = 
{
	section_menu:											"Testes de velocidade aos segmentos",
	section_title:											"Aqui pode testar a velocidade das gateways residenciais por segmentos, incluindo as gateways para a Internet e entre pontos de acesso.",
	section_scenes:											"Segmento:",
	section_ONT_Internet:									"Gateway para a Internet",
	section_ONT_AP:											"ponto de para Gateway acesso",
	section_AP_AP:											"Ponto de acesso a ponto de acesso",
	section_AP_Internet:									"Ponto de acesso para Internet",
	section_address:										"Endereço do servidor:",
	section_apmac:											"MAC do ponto de acesso:",
	section_clientmac:									    "MAC do cliente:",
	section_servermac:										"MAC do servidor:",
	section_advance:										"Definições avançadas:",
	section_status:											"Direção:",
	section_up:												"Carregar",
	section_down:											"Transferir",
	section_protocol:										"Protocolo:",
	section_TCP:											"TCP",
	section_UDP:											"UDP",
	section_port:											"Identificação da porta:",
	section_speedtime:										"Duração do teste:",
	section_listenime:										"Duração da escuta:",
	section_parallel:										"Número de transmissões simultâneas:",
	section_time10:											"10",
	section_time20:										    "20",
	section_time30:											"30",
	section_time40:											"40",
	section_time50:											"50",
	section_time60:											"60",
	section_listentime0:									"60",
	section_listentime1:									"600",
	section_listentime2:									"1200",
	section_listentime3:									"1800",
	section_listentime4:									"2400",
	section_listentime5:									"3000",
	section_listentime6:									"3600",		
	section_numb1:											"1",
	section_numb2:											"2",
	section_numb3:											"3",
	section_numb4:											"4",	
	section_apply:											"Iniciar",
	section_cancel:											"Parar",
	section_speeding:										"A testar...",
	section_speedresult:								    "Resultado",
	section_Attributes:										"Atributos",
	section_value:											"Valor",
    section_thesame:                                        "O MAC do cliente tem de ser diferente do MAC do servidor.",
    section_macnull:         		                    	"O endereço MAC não pode ficar em branco.",
    section_gateway:                                        "Gateway",
    section_internet:                                       "Internet",
    section_AP:                                             "AP",
    section_sampvaluetitle:                                 "Valor de amostra",
    section_clienterr:                                      "The Client startup failed!",
    section_mark1:                                          "(Duração do teste do cliente)",
    section_mark2:                                          "(Duração da escuta do servidor)",
	section_bandwidth:                                      "Largura de banda:",
	bandwidth_mark:                                         "(600 MB/s por defeito)",
	section_bandwidthNE:                                    "A largura de banda tem de ser um número inteiro superior a zero.",
    section_speedresultdetails:                             "Details",
    section_speedmax:                                       "Max",
    section_speedmin:                                       "Min",
    section_speedaverage:                                   "Average"
};
 
﻿
var AccountLgeDes =
{
	s0100:    "Nesta página, pode alterar a palavra-passe de início de sessão de um utilizador normal, definir a palavra-passe de autenticação do certificado SSL usado no acesso ao dispositivo via HTTPS e importar o certificado SSL correspondente.",
	s0101:    "alteração de senha",
	s0102:    "Gestão de Conta",
	s1902:    'A palavra-passe é demasiado fraca. Configure novamente.',
	s1904:    "A palavra-passe deve conter entre 1 a 127 carateres .",
	s0f01:    "A palavra-passe do utilizador comum foi alterada com sucesso.",
	s0f02:    "A nova palavra-passe não pode ficar em branco.",

	s0f04:    "A nova palavra-passe contém carateres inválidos. Introduza um válido.",

	s0f06:    "A palavra-passe confirmada é diferente da nova palavra-passe.",
	s0f07:    "Nesta página, pode alterar a palavra-passe de um utilizador comum, para torná-la mais fácil de lembrar e certificar a segurança.",
	s0f08:    "Nome de utilizador:",
	s0f09:    "Nova palavra-passe:",

	s0f0b:    "Confirmar palavra-passe:",
	s0f0c:    "Aplicar",
	s0f0d:    "Cancelar",
	s0f0e:    "Palavra-passe alterada com sucesso.",
	s0f0ea:   "Depois da alteração, a palavra-passe da telnet é sincronizada com a palavra-passe nova.",
	s0f0eb:   "A palavra-passe nova tem mais de 64 bits (o comprimento máximo da palavra-passe da telnet). Neste caso, a palavra-passe da telnet não vai ser sincronizada com esta nova palavra-passe. Tem a certeza de que pretende continuar? ",
	s0f0f:    "A palavra-passe antiga não pode ficar em branco.",
	s0f11:    "Palavra-passe antiga incorreta. Tente novamente.",
	s0f12:    "Nesta página, pode alterar a palavra-passe de início de sessão do utilizador atual, para torná-la mais fácil de lembrar e certificar a segurança.",
	s0f12a:   "Nesta página, é possível alterar a palavra-passe de início de sessão do utilizador actual, definir a palavra-passe de autenticação utilizando um certificado SSL para aceder ao CPE em modo HTTPS e importar o certificado SSL necessário.",
	s0f13:    "Palavra-passe antiga:",
	s0f14:    "Pista:",
	s0f15:    "A pista não pode estar vazia.",
    s0f16:    "A nova senha deve ser diferente da senha antiga em pelo menos dois locais.",
    s0f17:    "A nova senha deve ser diferente das últimas três senhas.",
	s1116:    "1.A palavra-passe deve conter pelo menos 6 carateres.<br/>2. A palavra-passe deve conter pelo menos duas das seguintes combinações: Digit, maiúsculas, minúsculas <br/>&nbsp;&nbsp;&nbsp;Carateres especiais (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ?).<br/>3.A palavra-passe não pode conter o nome de utilizador nem de forma alterada ou revertida.",
	s1116a:   "1.A palavra-passe deve conter pelo menos 6 carateres.<br/>2. A palavra-passe deve conter pelo menos duas das seguintes combinações: Digit, maiúsculas, minúsculas <br/>&nbsp;&nbsp;&nbsp;Carateres especiais (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ?).<br/>3.A palavra-passe não pode conter o nome de utilizador nem de forma alterada ou revertida.",
	ss1116b:  "1. Recomenda-se que a palavra-passe apenas contenha 6 caracteres.<br/>2. É recomendado que sejam adicionados pelo menos dois tipos dos seguintes caracteres sejam incluídos na palavra-passse: números, letras maiúsculas e minúsculas e caracteres especiais. Os caracteres especiais podem ser os seguintes:`~!@#$%^&*()-_=+|[{}];:'&lt;,.&gt;/?<br/>3. É recomendado que a palavra-passe não seja o nome do utilizador ou o nome do utilizador de trás para a frente.",
	ss1116c:  "1. Recomenda-se que a palavra-passe apenas contenha 6 caracteres.<br/>2. É recomendado que sejam adicionados pelo menos dois tipos dos seguintes caracteres sejam incluídos na palavra-passse: números, letras maiúsculas e minúsculas e sublinhados (_).<br/>3. É recomendado que a palavra-passe não seja o nome do utilizador ou o nome do utilizador de trás para a frente.",
	ss1116d:   "1.A palavra-passe deve conter pelo menos 8 carateres.<br/>2. A palavra-passe deve conter pelo menos duas das seguintes combinações: Digit, maiúsculas, minúsculas <br/>&nbsp;&nbsp;&nbsp;Carateres especiais (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ?).<br/>3.A palavra-passe não pode conter o nome de utilizador nem de forma alterada ou revertida.",
	s1116g:   "1.A palavra-passe deve conter pelo menos 10 carateres.<br/>2. A palavra-passe deve conter pelo menos duas das seguintes combinações: Digit, maiúsculas, minúsculas <br/>&nbsp;&nbsp;&nbsp;Carateres especiais (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ?).<br/>3.A palavra-passe não pode conter o nome de utilizador nem de forma alterada ou revertida.",
	
	s1117:    "A palavra-passe é fraca. Tem a certeza que pretende continuar?",
	s1118:    "<strong class=\"color_red\">A palavra-passe de início de sessão é a predefinida. Altere-a imediatamente.</strong>",

	s1119:    "Gestão ONT",
	s1119_xd: "Gestão Home Gateway",	
	s1120:    "Alterar Palavra-passe de Gestão",
	s1121:    "Guardar",
	s1122:    "Reinício e Recuperação de Configurações",
	s1123:    "Reiniciar",
	s1124:    "Restaurar Predefinições",
	s1125:    "Clique para restaurar o dispositivo.",
	s1126:    "Clique para restaurar o dispositivo para as suas configurações predefinidas.",
	s1127:    "Restaurar Predefinições",
	s1128:    "",

    s1201:    'Restaurar configurações de fábrica do Ap',
    s1202:    'Selecione o MAC do AP:',
    s1203:    'Clique nele para restaurar o AP selecionado para a configuração de fábrica.',
    s1204:    'Restaurar configurações de fábrica do AP',
    s1205:    "Se você restaurar os padrões de fábrica de ap, os dados definidos pelo usuário de ap serão perdidos e o ap será reiniciado. Você tem certeza que quer continuar?",
    s1206:    'Falha ao restaurar a configuração padrão do AP.',

	s0d21:    "Aplicar",
	s0d22:    "Cancelar",

	s0d23:    "Ativar certificado de autenticação e definir palavra-passe de chave privada",
	s0e23:    "Ativar certificado de autenticação e definir palavra-passe de chave privada",
	s0d25:    "Ativar certificado de autenticação:",
	s0d26:    "Palavra-passe de chave privada:",
	s0d28:    "Confirmar palavra-passe:",
	s0d29:    "Importar certificado",
	s0e29:    "Importar certificado",
	s0d2a:    "Certificado:",
	s0d2b:    "Procurar",
	s0d2c:    "Importar certificado",
	s0d10:    "Selecione  um diretório  de ficheiro.",
	s0d11:    "O comprimento do diretório  de ficheiro não pode exceder 128 carateres.",
	s0d0f:    "A palavra-passe confirmada é diferente da palavra-passe de chave privada.",
	s0d14:    "Palavra-passe de chave privada alterada com sucesso. Tem efeito após reiniciar o dispositivo.",
	s1430:    "O palavra-passe não pode estar em branco. Tente novamente.",
	s1901:    'Nesta página, pode definir a palavra-passe de autenticação SSL utilizada para aceder ao ONT utilizando HTTPS e importar o certificado SSL correspondente.',
	s1902:    'A palavra-passe é demasiado fraca. Configure novamente.',
	s1903:    'Gestão de Certificado SSL',
	s1904:    "A palavra-passe deve conter entre 1 a 127 carateres .",
	s1904a:    "A palavra-passe deve conter entre 8 a 64 carateres .",
	s1905:    "(1-127 carateres. A palavra-passe tem efeito após a reiniciar o dispositivo.)",

	s2000:    "Altere a palavra-passe do início de sessão.",
	s2001:    "Anterior",
	s2002:    "Seguinte",
	s2003:    "Próximo",
	s2004:    "Sair",
	
	s1447:  "Força da senha:",
    s1448:  "Fraca",
    s1449:  "Média",
    s1450:  "Forte",

	s2010:    "Requisitos de palavra-passe",
	s2011:    "A palavra-passe deve conter pelo menos 6 carateres.",
	ss2011a:  "A palavra-passe deve conter pelo menos 8 carateres.",
	s2012:    "A palavra-passe deve conter pelo menos duas das seguintes combinações: Digit, maiúsculas, minúsculas, Carateres especiais (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ? ).",
	s2013:    "A palavra-passe não pode conter o nome de utilizador nem de forma alterada ou revertida.",
	s2200: "Falha ao alterar a palavra-passe.",
	s2300: "Alterar Senha",
	s2301: "Altere a senha do Vivo Box, digitando a senha atual uma vez e repetindo duas a sua nova senha.</br>Sugerimos que você anote sua nova senha após a alteração. ",
	s2302: "Senha Atual:",
	s2303: "Nova Senha:",
	s2304: "(confirme)",
	s2305: "Salvar",
	s2306: "Cancelar",
	s2501: "Restaurar configuração",
	s2502: 'Pode clicar em "Restaurar configuração" para restaurar as configurações de um terminal de um ficheiro de backup de configuração.',
	s2503: 'Selecionar ficheiro de backup de configuração:',
	s2504: 'Restaurar configuração',

	s2801: "Password",
	s2802: "Defina uma password para restringir o acesso de administração ao router.",
	s2803: "Nome de utilizador",
	s2804: "Redefinir Password",
	s2805: "Login",
	s2806: "Logout automático",
	s2807: "5 Minutos",
	s2808: "10 Minutos",
	s2809: "15 Minutos",
	s2810: "30 Minutos",
	s2811: "Segurança da conta",
	s2812: "Permitir que equipamentos no lado do Wi-Fi acedam a interface de gestão",
	s2813: "Serviço Wi-Fi",
	s2814: "Alterar Password",
	s2815: "Digite uma password para o seu Advanced Router",

	s2816: "Segurança da password",
	s2817: "Muito fraco",
	s2818: "Está bem",
	s2819: "A password deve ter pelo menos 8 caracteres e deve conter letras maiúsculas ou minúsculas e pelo menos um número.",
	s2820: "A password digitada não corresponde aos requisitos mínimos de segurança.",
	s2821: "As password não correspondem.",

	s2701: "Tem certeza de que deseja redefinir a password?",
	s2703: "Palavra-passe redefinida com sucesso!",
	s2704: "Falha ao redefinir senha!"
};
 
﻿
var ApmcfgLgeDes = 
{
	s0100: 	  "Gestão de Energia Avançada",
	s0e01:    "Nesta página, pode definir o consumo de energia para o dispositivo.",
    s0e02:    "Configuração do baixo consumo de energia",
    s0e03:    "Ativar baixo consumo de energia:",
    s0e04:    "Ativar serviços em modo bateria",
    s0e05:    "Serviço",
    s0e06:    "Ativar",
    s0e07:    "Gestão remota:",
    s0e08:    "Aplicar",
    s0e09:    "Cancelar",
    s0e0a:    "VOZ:"
};
  
﻿
var BatteryinfoLgeDes = 
{ 
    s0101:    "Nesta página, pode ver o modo de fornecimento de energia e capacidade da bateria disponível.",
    s0102:    "Modo de Fornecimento de Energia:",
    s0103:    "Bateria",
    s0104:    "Energia comercial",
    s0105:    "Capacidade de Bateria Disponível:"
};
 
﻿
var BssLgeDes = 
{
	s0100:	  "Estado de Fornecimento de Serviço",
	s1300:    "Nesta página, pode ver o estado do fornecimento de serviço.",
	s1301:    "Estado de Registo ONT:",
	s1302:    "--",
	s1303:    "O ONT foi registado com o OLT. Aguarde por favor.",
	s1304:    "ONT e o OLT foram registados com sucesso.",
	s1305:    "Atualizar",
	s1306:    "Expirou tempo de registo com a OLT. As causas possíveis são as seguintes: <br/>1. A fibra ótica não está ligada ou a energia ótica é irregular. <br/> 2. A informação de autenticação PON está incorreta. <br/>Se a mencionada informação estiver correta , contacte um centro de serviços ao cliente.",
	s1307:    "Estado de configuração de serviço OLT:",
	s1308:    "O OLT está a aplicar as configurações. Aguarde por favor.",
	s1309:    "Serviço OLT configurado com sucesso.",
	s130a:    "Falha ao configurar o serviço OLT.",
	s130b:    "Falha a obter o estado devido à versão OLT não corresponder.",
	s130c:    "Estado de configuração EMS:",
	s130d:    "Sem configurações XML aplicadas.",
	s130e:    "O EMS está a aplicar as configurações.",
	s130f:    "Serviço EMS configurado com sucesso.",
	s1310:    "Falha ao configurar o serviço EMS.",
	s1311:    "Estado de Registo ACS:",
	s1312:    "O ONT está à espera para ser registado com o servidor ACS. Aguarde por favor.",
	s1313:    "O ONT foi registado com o servidor ACS. Aguarde por favor.",
	s1314:    "Registado no servidor ACS com sucesso.",
	s1315:    "Falha a registar com o servidor ACS.",
	s1316:    "A versão ONT não é compatível com a versão OLT. Substitua o ONT.",
	s1317:    "A obter o estado. Aguarde...",
	
	s2000:"Configuração concluída. A emitir serviços...",
	s2001:"Voltar à Página Inicial",
	s2002:"O ONT está a efectuar registo com o OLT... Aguarde.",
	s2003:"Serviço emitido com sucesso. Bem-vindo.",
	s2004:"O EMS está a emitir configurações. Aguarde.",
	s2005:"Falha na configuração de serviço no EMS. Verifique as definições EMS.",
	s2006:"Registo efectuado com o ACS.",
	s2007:"O ONT está a efectuar registo com o servidor ACS... Aguarde.",
	s2008:"A ONT falhou a efectuar o registo com o ACS.",
	s2009:"Expirou tempo de registo com a OLT. As causas possíveis são as seguintes: <br/>1. A fibra ótica não está ligada ou a energia ótica é irregular. <br/> 2. A informação de autenticação PON está incorreta. <br/>Se a mencionada informação estiver correta , contacte um centro de serviços ao cliente.",
	s2010:"Falha na configuração de serviço no OLT.",
	s2011:"O OLT está a emitir configurações. Aguarde.",
	s2012:"Falha ao obter o estado porque a versão OLT não corresponde.",
	s2013:"Fornecimento de serviço incompleto. Navegue até à página inicial e clique no separador de Estado de Fornecimento de Serviço no lado esquerdo da página para visualizar a informação de fornecomento de serviço."
};
 
﻿
var CfgfileLgeDes = 
{ 
	s0100:   "Nesta página, é possível armazenar, transferir e actualizar o ficheiro de configuração.",
	s0101:   "Guardar Configurações e Repor definições",
	s0102:    "Gestão do ficheiro de configur.",
	s0905:    "O sistema está ocupado. Tente novamente mais tarde.",
    s0701:    "Ficheiro de configuração guardado com sucesso.",
    s0702:    "O diretório  do ficheiro não pode ficar em branco.",
    s0703:    "O comprimento do diretório  não pode exceder 128 carateres .",
    s0704:    "O ficheiro é demasiado grande.",
    s0705:    "Ficheiro inválido ou inexistente.",
    s0706:    "Tem a certeza que pretende guardar as configurações e reiniciar o terminal?",
    s0707:    "Nesta página, pode guardar o ficheiro de configuração atual  para a memória flash.</br>Também poderá guardar os ficheiros de configuração atuais  para a memória flash e ativar  o reinício automático do dispositivo.",
    s0709:    "Guardar",
    s070a:    "Guardar e Reiniciar",
    s070b:    "Pode transferir o ficheiro de configuração atual  para o computador atual .",
    s070c:    "Transferir ficheiro de configuração",
    s070d:    "O terminal pode ser atualizado  a partir do ficheiro de configuração. Guarde o ficheiro se no diretório  pretendido e clique em Atualização  de Ficheiro de Configuração.",
    s070e:    "Ficheiro de configuração:",
    s070f:    "Procurar",
    s0710:    "Atualizar  ficheiro de configuração",
	s0711:	  "Se importar o ficheiro de configuração, o terminal irá reiniciar e as definições irão ter efeito. Tem a certeza de que pretende continuar?",
	
	s0a01:    "Se restaurar as configurações predefinidas, as definições de utilizador serão perdidas após o reinício. Tem a certeza que pretende continuar?",
    s0a02:    "Nesta página, pode restaurar as configurações predefinidas.",
    s0a03:    "Predefinição",

    s0b00:    "Baixar arquivo de configuração do AP",
    s0b01:    "Tipo de dispositivo",
    s0b02:    "Endereço MAC",
    s0b03:    "SN",
    s0b04:    "Tipo de dispositivo:",
    s0b05:    "Endereço MAC:",
    s0b06:    "SN:",
    s0b07:    "Coletar configuração de AP",
    s0b08:    "Download da configuração do AP",
    s0b09:    "Coleção de arquivos de configuração do AP, aguarde ...",
    s0b10:    "O arquivo de configuração do AP é coletado!",
    s0b11:    "Falha ao coletar a configuração do AP.",

    s1001:    "Configuração",
    s1002:    "A partir daqui pode guardar a sua configuração, restaurar uma configuração salva anteriormente e restaurar o seu router para a sua configuração padrão.<br><br>O seu router pode guardar uma versão da configuração internamente, ou pode salvar a configuração num computador ou local de rede.",
    s1003:    "Guardar definições no computador",
    s1004:    "Guardar",
    s1005:    "Restaurar uma configuração guardada num PC",
    s1006:    "Restaurar",
    s1007:    "Redefinir configurações de fábrica",
    s1008:    "Clicar em Reiniciar permite restaurar o router para as configurações de fábrica e forçar uma reinicialização.",
    s1009:    "Reiniciar",

    ss0a10:    "O tipo de ficheiro está errado; verifique por favor se é o ficheiro de configuração antigo transferido antes",

    Cfgfile001:   "Guardar configuração no computador",
    Cfgfile002:   "Por favor, adicione um comentário que descreva esta configuração.",
    Cfgfile003:   "Crie uma password para proteger seus dados.",
    Cfgfile004:   "Restaurando a configuração em andamento",
    Cfgfile005:   "Carica configurazione dal computer",
    Cfgfile006:   "Criado em",
    Cfgfile007:   "Versão de Firmware",
    Cfgfile008:   "Descrição da configuração",
    Cfgfile009:   "Esta configuração é protegida por password.",
    Cfgfile0010:   "Digite a password",
    Cfgfile0011:   "A password deve ter pelo menos 8 caracteres e deve conter letras maiúsculas ou minúsculas e pelo menos um número.",
    Cfgfile0010:   "A password digitada não corresponde aos requisitos mínimos de segurança.",
    Cfgfile0012:   "As password não correspondem.",
    Cfgfile0013:   "Segurança da password",
    Cfgfile0014:   "Muito fraco",
    Cfgfile0015:   "Fraca",
    Cfgfile0016:   "Está bem",
    Cfgfile0017:   "Forte"
};
 
﻿
var CfgguideLgeDes = 
{ 
	s1116:    "1.A palavra-passe deve conter pelo menos 6 carateres.<br/>2. A palavra-passe deve conter pelo menos duas das seguintes combinações: Digit, maiúsculas, minúsculas <br/>&nbsp;&nbsp;&nbsp;Carateres especiais (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ?).<br/>3.A palavra-passe não pode conter o nome de utilizador nem de forma alterada ou revertida.",
	s0f0f:    "A palavra-passe antiga não pode ficar em branco.",
	s0f02:    "A nova palavra-passe não pode ficar em branco.",
	s0f04:    "A nova palavra-passe contém carateres inválidos. Introduza um válido.",
	s0f06:    "A palavra-passe confirmada é diferente da nova palavra-passe.",
	s0f11:    "Palavra-passe antiga incorreta. Tente novamente.",
	s1902:	  'A palavra-passe é demasiado fraca. Configure novamente.',
	s1904:    "A palavra-passe deve conter entre 1 a 127 carateres .",
	
	s2000:    	"Método de Fornecimento de Serviço",
	s2001:    	"No OLT",
	s2002:    	"Serviços para o ONT são configurados no OLT.",
	s2003:    	"No EMS",
	s2004:    	"Serviços para o ONT são configurados no EMS.",
	s2005:    	"No ACS",
	s2006:    	"Serviços para o ONT são configurados no ACS.",
	s2007:    	"Na página de Internet ONT",
	s2008:    	"Serviços para o ONT são configurados na página de Internet ONT.",
	s2009:    	"Sair",
	s2010:    	"Seguinte",
	s2011:    	"Copyright © 2022 Huawei Technologies Co., Ltd. Todos os direitos reservados.",
	s2012_xd:    	"Bem-vindo ao Home GateWay Huawei, ligando-o à sua família e amigos.",
	
	s2012:    	"Bem-vindo ao ONT Huawei, ligando-o à sua família e amigos.",
	s2013:    	"Autenticação ONT",
	s2014:    	"Configuração de WAN",
	s2015:    	"Conclusão de configuração",
	
	s2016:    	"Configuração de Internet",
	s2017:    	"Configuração de Wi-Fi",
	s2018:    	"Gestão de conta",
	
	s2019:    	"Configuração concluída. Bem-vindo.",
	s2020:    	"Anterior",
	s2021:    	"Voltar à Página Inicial",
	
	s2040:      "Modo de ligação à rede actual: ",
	s2041:      "Com fios",
	s2042:      "Wi-Fi",
	s2043:      "Se modificou os parâmetros Wi-Fi, tente a ligação novamente.",
	s2044_xd:   "Navegue para a página inicial e comece a utilizar o Home Gateway.",	
	s2044:      "Navegue para a página inicial e comece a utilizar o ONT."
};
 
﻿
var CollectInfoLgeDes = 
{ 
    s1101:    "Ativar recolha de informações de falhas",
    s1102:    "Nesta página, pode recolher e transferir informação de falhas.",
    s1104:	  "Iniciar",
    s1114:	  "Transferir",
    s1119:    "A recolher informação de falhas...Aguarde um momento.",
    s1120:    "Informação de falhas recolhidas com sucesso.",
    s1122:    "Ativar Coletar informações de falha de AP",

    s2001:    "Ferramenta de diagnóstico",
    s2002:    "Esta seção mostra uma lista de ferramentas que podem ser usadas para verificar o status de suas conexões de rede.",
    s2003:    "Diagnóstico automático",
    s2004:    "O diagnóstico demora cerca de 2 minutos e não pode ser cancelado depois de iniciado.",
    s2005:    "Teste de Ping",
    s2006:    "Digite um nome de computador ou endereço IP válido para fazer um teste de ping.",
    s2007:    "Teste de trace route",
    s2008:    "Digite um nome de computador ou endereço IP válido para fazer um teste de rastreamento de rastreio.",
    s2009:    "Ativar informações de falha de coleta",
    s2010:    "Pode obter e transferir informações sobre falhas.",
    s2011:    "Diagnóstico",
    s2012:    "Ping",
    s2013:    "Trace",
    s2014:    "Começar",
    s2015:    "Download",
    s2018:    "Repita primeiro uma WAN da Internet!",
    s2019:    "Antes de restaurar uma configuração antiga, verifique se guardou a configuração atual.",
    s2020:    "Diagnóstico em progresso",
    
    s2021:    "LAN",
    s2022:    "Concluído com sucesso",
    s2023:    "Número de equipamentos de LAN:",
    s2024:    "WAN",
    s2025:    "Modo WAN",
    s2026:    "Status do link",
    s2027:    "Conectado",
    s2028:    "Desligado",
    s2029:    "Ligação de dados IP",
    s2030:    "Ligação de dados PPP",
    s2031:    "Ligação IP de voz",
    s2032:    "Ligação de voz PPP",
    s2033:    "Telefone",
    s2034:    "Linha ",
    s2035:    "USB",
    s2036:    "Número de equipamentos USB:",
    s2037:    "Wi-Fi",
    s2038:    "Desativo",
    s2039:    "Habilitada",
    s2040:    "Teste de conectividade",
    s2041:    "Teste falhou",
    s2042:    "Diagnóstico concluído"
};

var cfg_wifiinfo_dfx_language =
{
    amp_dfx_title:                    'Recolha de informações Wi-Fi',
    amp_dfx_ppdu_col_time_int:        'O número de recolhas tem de ser um número inteiro.',
    amp_dfx_ppdu_col_time_range:      'O número de recolhas deverá situar-se entre 0 e 360.',
    amp_dfx_csi_col_time_num_int:     'O número de recolhas tem de ser um número inteiro.',
    amp_dfx_csi_col_time_num_range:   'O número de recolhas deverá situar-se entre 1 e 1000.',
    amp_dfx_sdt_feature_empty:        'A função SDT não pode estar vazia.',
    amp_dfx_sdt_feature_invalid:      'A função SDT contém caracteres inválidos.',
    amp_dfx_packet_condition_empty:   'Selecione um tipo de pacote a ser rastreado.',
    amp_dfx_btn_text:                 'Mostrar diagnóstico Wi-Fi',
    amp_dfx_btn_hide_text:            'Ocultar diagnóstico Wi-Fi',
    amp_dfx_type:                     'Tipo de diagnóstico:',
    amp_dfx_type_keyrecord:           'Recolher informações básicas',
    amp_dfx_type_ppdu:                'Recolher PPDU',
    amp_dfx_type_csi:                 'Recolher CSI',
    amp_dfx_type_sdt:                 'Recolher SDT',
    amp_dfx_type_packet:              'Rastrear pacotes',
    amp_dfx_type_fw:                  'Exportar dados de firmware',
    amp_dfx_frequency:                'Banda de frequência:',
    amp_dfx_2g:                       '2,4 GHz',
    amp_dfx_5g:                       '5 GHz',
    amp_dfx_col_time:                 'Número de recolhas:',
    amp_dfx_ppdu_col_time_note:       'minutos (0–360; valor predefinido:10)',
    amp_dfx_start:                    'Iniciar',
    amp_dfx_stop:                     'Parar',
    amp_dfx_csi_stamac:               'Endereço MAC do STA:',
    amp_dfx_csi_stamac_select:        'Selecionar...',
    amp_dfx_csi_col_time_num:         'Número de recolhas:',
    amp_dfx_csi_col_time_num_note:    '(1–1000)',
    amp_dfx_sdt_feature:              'Função:',
    amp_dfx_sdt_set:                  'Definir',
    amp_dfx_sdt_clearall:             'Limpar tudo',
    amp_dfx_packet_condition:         'Tipo:',
    amp_dfx_packet_condition_all:     'Selecionar tudo',
    amp_dfx_download_log:             'Transferir registos',
    amp_dfx_download_run_log:         'Transferir registos de execução',
    amp_dfx_download_hist_log:        'Transferir registos do histórico'
};
 
﻿
var DebuglogviewLgeDes = 
{ 
	s0100:    "Nesta página, é possível transferir e consultar registos de depuração.",
	s0101:    "Registo de depuração",
	s0b0f:    "Transferir e Ver registos",
    s0b10:    "Pode ver e transferir ficheiros de registos.",
    s0b11:    "Transferir ficheiro de registo",
    s0b14:    "Tipo de registo:",
    s0b19:    "Registo de depuração",
    s0b20:    "Registo WiFi",
    s0b21:    "Registo de consulta"
};
 
﻿var DevInfoDes = 
{ 
    s0200:    "Infor. do dispositivo",
	s0201:    "Nesta página, pode ver informações gerais do dispositivo.",
    s0202:    "Tipo de dispositivo:",
    s0203:    "Descrição:",
    s0204:    "Versão de Equipamento Informático:",
    s0205:    "Versão de Programa Informático:",
    s0206:    "Estado de Registo ONT:",
    s0207:    "ID de ONT:",
    s0208:    "Utilização de CPU:",
    s0209:    "Utilização de memória:",
    s020a:    "XML Alias:",
	s020b:    "Não registado e não autorizado",
	s020c:    "Registado e autorizado",
	s020d:    "Registado e não autorizado",
	s020e:	  "Tempo de execução do dispositivo:",
	s020f:    "dia",
	s0210:    "hora",
	s0211:    "minuto",
	s0212:    "segundo",
	s0213:    "dias",
	s0214:    "horas",
	s0215:    "minutos",
	s0216:    "segundos",
 	s0217:    "Info. de fabricante:",
	s0225:   "Inform. personalizada:",
	s0226:    "Hora do Sistema:",
	s1321:    "A versão ONT não é compatível com a versão OLT. Substitua o ONT.",
	s1322:    "(Estado inicial)",
	s1323:    "(Estado de espera)",
	s1324:    "(Estado do número de série)",
	s1325:    "(Estado de variação)",
	s1326:    "(Estado de operação)",
	s1327:    "(Estado POPUP)",
	s1328:    "(Paragem de emergência)",
	s1611:"N.º de série:",
	s1612:"Mac:&nbsp;",
	s1616:	  "Informações avançadas",
	s1617:    "Nome do dispositivo:",
	s1618:    "Guardar",
	s1619:    "Informações básicas",
	s2016:    "O administrador está a utilizar a palavra-passe inicial. Se pretender alterar esta palavra-passe, contacte a operadora de telecomunicações. Para mais detalhes sobre como alterar a palavra-passe, consultar Gestão de Segurança a partir da página http://support.huawei.com.",
	s2016_ebg:    "O administrador está a utilizar a palavra-passe inicial. Se pretender alterar esta palavra-passe, contacte a operadora de telecomunicações. Para mais detalhes sobre como alterar a palavra-passe, consultar Gestão de Segurança a partir da página http://support.huawei.com/enterprise."
};
 
﻿
var DlnaLgeDes =
{
	s0526:"Aplicar",
	s0527:"Cancelar",
	s0531:"Atenção:",
	s0532:"Não remova e volte a inserir o dispositivo de armazenamento USB em utilização. Esta acção poderá danificar os ficheiros do dispositivo.",
	s1410:"Partilhar diretório :",
	s1436:"Procurar diretório",
	s1600:"No serviço de partilha de multimédia, pode partilhar informação multimédia para dispositivos que suportem DLNA. Por exemplo, pode partilhar vídeos, áudio e fotos para computadores, dispositivos móveis e aparelhos de consumo. Nesta página, pode configurar os serviços de partilha e partilhar diretórios.",
	s1601:"Ativar autenticação multimédia:",
	s1602:"Partilhar diretório:",
	s1603:"Todos os diretórios",
	s1604:"Especifique diretório",
	s1605:"Procurar",
	s1606:"Pode ser configurado até um máximo de 10 diretórios partilhados.",
	s1607:"O diretório não pode estar em branco. Especifique um diretório.",
	s1608:"O diretório já está na lista. Introduza outro.",
	s1609:"Diretório especificado:",
	s1610:"O comprimento do diretório especificado ultrapassa o limite.",
	s1611:"Partilha multimédia DLNA",
	s1975:"O serviço ativado utiliza protocolos inseguros. É aconselhado ter o serviço desativado por predefinição",

	dlna001:    "Ativar DLNA Digital Media server",
	dlna002:    "Idioma do servidor de mídia digital DLNA",
	dlna003:    "Nome do servidor DLNA",
	dlna004:    "Endereço IP do servidor DLNA",
	dlna005:    "Compartilhe todas as pastas",
	dlna006:    "Inglês",
	dlna007:    "O DLNA Digital Media Server oferece a capacidade de transmitir música, vídeo e fotos.",
	dlna008:    "Lembre-se de que este serviço está desativado por default. Recomendamos que, por motivos de segurança, desative esses serviços quando não os usar"
};
 
﻿
var FirmwareLgeDes = 
{ 
	s0900:	  "Actualização de Software",
    s0901:    "Selecione  um ficheiro suporte lógico.",
    s0902:    "O comprimento do diretório  do ficheiro firmware não pode exceder 128 carateres .",
    s0903:    "Firmware é demasiado grande.",
    s0904:    "inválido ou inexistente.",
    s0905:    "O sistema está ocupado. Tente novamente mais tarde.",
    s0906:    "Nesta página, pode usar a função de atualização  de firmware para atualizar  o programa do terminal para a versão original.",
    s0906a:   "Nesta página, pode utilizar a atualização do ficheiro de versão para a atualizar a versão do software do terminal para a sua versão esperada. Se ativar a atualização automática, o terminal atualiza automaticamente a versão de firmware a partir do servidor remoto. ",
    s0907:    "Ficheiro de Firmware:",
    s0908:    "Procurar",
    s0909:    "Atualizar ",
	s090a:"Configuração da atualização automática ",
	s090b:"Actualiz. local",
    s090c:"Ativar a atualização automática",

    s1128:    "É possível atualizar o firmware do router. Suas opções de configuração personalizadas não serão afetadas pela atualização.",
    s1129:    "Versão atual do firmware",
    s1130:    "Nenhum ficheiro selecionado.",
    s1131:    "Selecione o ficheiro",
    s1132:    "Instalar atualização",
    s1133:    "Chamadas telefónicas, conexões de Internet e conexões LAN serão interrompidas devido à atualização. Por favor, clique em Aplicar se pretender continuar.",
    s1134:    "Confirmar",
    s1135:    "Download do firmware",
    s1136:    "O firmware está a ser atualizado no Vodafone Smart Router.",
    s1137:    "Instalação de firmware atualizada",
    s1138:    "Não desligue o Vodafone Smart Router.",
    s1139:    "Firmware atualizado corretamente",
    s1140:    "O seu Vodafone Smart Router está a reiniciar. Por favor, não desligue ou pressione qualquer botão até que ele seja reiniciado.",
    s1141:    "A atualização do firmware falhou",
    s1142:    "Pode haver um texto explicando a falha",
    s1143:    "Cancelar",
    s1144:    "Atualização de Firmware"
};
 
﻿
var forceSupportLangDes = 
{
	s0100: "点击此按钮可以关闭强推功能",
	s0101: "关闭强推"
};
  
﻿
var LedcfgLgeDes = 
{ 
	s0100: 	  "Config Painel de Luzes", 
	s0e08:    "Aplicar",
    s0e09:    "Cancelar",
	s1500:	  "Nesta página pode programar o seu equipamento para desligar todas as luzes do painel frontal do dispositivo (menos a luz de power). Poderá indicar uma janela temporal em que tem efeito esse desligamento.",
	s1501:    "Configuração do interruptor do indicador",
	s1801:    "Hora inicial",
	s1802:    "Hora final",
	s1803:    "Interruptor do indicador",
	s1804:    "Período de inatividade do indicador",
	s1805:    ":",
	s1806:    "(00:00-23:59)",
	s1807:	  'O número de períodos configurados chegaram ao limite permitido. Não tem permissão para adicionar mais.',
	s1808:    "Ligado",
	s1809:	  'Desligado',
	s1810:	  'Hora inicial inválida.',
	s1811:	  'Hora final inválida.',
	s1812:	  'A hora introduzida está inválida. Introduza um valor entre 00 e 23.',
	s1813:	  'Os minutos introduzidos estão inválidos. Introduza um valor entre 00 e 59.',
	s1814:	  'O período especificado está inválido. A hora inicial deve começar antes da hora final. ',
	s1815:	  'Nenhuma regra de período está configurada.',
	s1816:	  'Especifique um período.',
	s1817:	  'O período especificado sobrepõe um período previamente configurado. Especifique outro período.',
	s1818:	  'Configuração do período de inatividade do indicador'

};
 
var PrompterDes = 
{ 
	s1005:	  "Falha a atualizar. Selecione o ficheiro correto  e tente novamente. Nota: O dispositivo não pode ser atualizado  se o tipo de ficheiro selecionado  está incorreto.",
	s1010:    "Reiniciar",
	s1012:    "Falha ao atualizar o ficheiro de configuração. Selecione o ficheiro correto  e tente novamente.",
	s1012vdf: "Falha ao atualizar o ficheiro de configuração, a senha pode estar errada.",
	s1015:    "Repetir",
	s1316:    "Falha a fazer cópia de segurança do ficheiro de configuração para o dispositivo USB.",
	s1317:    "Cópia de segurança do ficheiro de configuração para dispositivo USB concluída com sucesso.",
	s1318:    "Falha ao importar os certificados. Selecione o ficheiro correto e tente novamente.",
	s1319:    "Certificado importado com sucesso.",
	s131a:    "Ficheiro de configuração atualizado com sucesso. O sistema irá reiniciar. Aguarde por favor.",
	s131b:    "Falha ao transferir ficheiro. As possíveis causas são as seguintes:<br>1. O ficheiro não existe.<br>2. Os parâmetros foram definidos incorretamente.<br>3. O sistema está ocupado.",
	s131c:    "Falha ao restaurar as configurações predefinidas.",
	s131d:    "Configuração restaurada com sucesso. O sistema irá reiniciar. Aguarde por favor.",
	s131e:    "A configuração atual no dispositivo é a mesma que a configuração predefinida.",
	s131f:    "Atualização efetuada com êxito. Clique no botão Reiniciar para reiniciar o dispositivo e, em seguida, ative o ficheiro. <br/> Poderá existir um problema de compatibilidade do navegador após a atualização. Portanto, é recomendado fechar o navegador e iniciar sessão novamente após o dispositivo reiniciar.",
	s131f1:   "Atualização efetuada com êxito. Clique no botão Reiniciar para reiniciar o dispositivo e, em seguida, ative o ficheiro.",
	s1320:    "Tem a certeza que pretende reiniciar o dispositivo?",
	s1321:    "Aviso: Poderá não conseguir iniciar a sessão se o número de utilizadores ultrapassar o limiar ou o utilizador já iniciou a sessão."
};
 
﻿var SmartDiagnoseLgeDes = 
{
	s1900:    	'A ligação à Internet é anormal', 
	s1901:      'RF module chip fault.',
	s1902:      'DECT chip fault',
	s2000:	    'Falha no chip SD5113.',
	s2001:      'Falha no chip Wi-Fi.',
	s2002:		'Falha no chip LSW.',
	s2003:		'Falha no chip do codec.',
	s2004:		'Falha no chip do módulo ótico.',
	s2005:		'Falha no chip PHY.',
	s2006:		'O chip de reencaminhamento MAC é anormal;',
	s2007:		'O chip de reencaminhamento PHY é anormal;',
	s2008:		'Hardware ONT normal',
	s2009:		'Hardware ONT não está normal',
	s2009_xd:	'Hardware DSL não está normal',	
	s2010:    	'Ligação à Internet normal',
	s2011:    	'Falha na marcação PPPoE',
	s2012:    	'Falha na marcação DHCP',
	s2013:    	'Estado de Ligação à Internet',
	s2014_xd:   'Estado do Hardware Home Gateway',	
	s2014:    	'Estado do Hardware ONT',
	
	s2015:    	'Diagnóstico rápido',	
	s2016:    	'A diagnosticar...',
	s2017:    	'O resultado do diagnóstico é normal.',	
	s2018:    	'O resultado do diagnóstico não é normal. Resolva a anormalidade.',	
	s2019:    	'Diagnosticar novamente',	
	s2020:    	'Grau de segurança da palavra-passe',	
	s2021:    	'Grau de segurança da palavra-passe do utilizador',
	s2022:    	'Baixo',
	s2023:    	'Alto',	
	s2024:    	'Grau de segurança da palavra-passe do Wi-Fi',
	s2025:      'O directório óptico está normal.',
	s2026:      'O directório óptico não está normal. Verifique as ligações de fibra ópticas.',
	s2027:      'Registo com OLT bem sucedido.',
	s2028:      'Registo com OLT falhou. Verifique os parâmetros de registo.',
	s2029:      'Este método de diagnóstico aplica-se apenas a uso por parte de um técnico especializado, pois pode afetar o serviço. Por favor, proceda com precaução ao utilizar este método de diagnóstico.',
	
	s3000:      'Estado de serviço de voz',
	s3001:      'Normal',
	s3002:      'Porta',
	s3003:      'A testar...',
	s3004:      'Nenhum serviço de voz configurado',
	s3005:      'Serviço de voz fechado',
	s3006:      'Falha no registo',
	s3007:      'Resultado de teste Loop não é normal',
	s3008:      'Ligação de rede de voz não é normal',
	s3009:      'erro desconhecido',
	s3010:      'O teste cíclico não é implementado porque há outras portas em chamadas',
	
	s3014: 		'Estado da gateway do serviço de IPTV',
	s3015: 		'A porta STB integrada está normal',
	s3016: 		'A porta STB incorporada é anormal. Contacte a operadora para obter assistência.',
	s3017: 		'As configurações de IPTV estão normais',
	s3018: 		'As configurações IPTV do gateway estão incorretas. Verifique as configurações das portas WAN.',
	s3019: 		'A rede de IPTV da gateway está normal.',
	s3020: 		'A rede IPTV do gateway é anormal. Verifique o estado da ligação da porta WAN.',
	s3021: 		'O serviço IPTV do gateway é normal.',
	s3022: 		'O STB incorporado não tem tráfego.',
	s2008lanap:	'O estado do hardware do dispositivo é normal.',
	s2009lanap:	'O hardware do dispositivo não funciona corretamente.',
	s2010ap:	'O estado da ligação da porta a montante é normal.',
	s2013ap:    'Estado da ligação da porta a montante',
	s2014lanap: 'Estado do hardware do dispositivo',
	s1900ap:    'O estado da ligação da porta a montante é anormal.',
	s3023:      'O modo de marcação PPPoE é manual. Execute a marcação manualmente.'

};
 
﻿var ConfigMainUpportDes = 
{
	sCMU000:"Nesta página, pode configurar as portas a montante ativas e em espera. A nova configuração é aplicada após o reinício de um dispositivo.",
	sCMU001:"Configuração de porta a montante",
	sCMU002:"Porta a montante ativa:",
	sCMU003:"Ativar porta a montante em espera",
	sCMU004:"Porta a montante em espera",
	sCMU005:"Aplicar",
	sCMU006:"Cancelar"
};
 
﻿
var PluginStatusLgeDes = 
{
	s0100:    "Estado da ligação entre o gateway inteligente e a plataforma de gestão da aplicação",
    s0301:    "Nesta página, pode consultar o estado das ligações entre o dispositivo e o gateway inteligente e entre a plataforma de gestão da aplicação.",
    s0302:    "Estado da ligação da plataforma de distribuição:",
    s0303:    "A tentar ligar à plataforma",
    s0304:    "",
    s0305:    "",
    s0306:    "",
    s0307:    "",
    s0308:    "Estado de ligação do centro de registo da plataforma de operação:",
    s0309:    "",
    s030a:    "A efetuar o registo na plataforma",
    s030b:    "Em heartbeat (keep-alive) com a plataforma",
    s030c:    "Estado de ligação do centro de plug-ins da plataforma de operação:",
    s030d:    "Não ligado"
};
 
var Reboot = 
{
    s1721:"Ativar:",
    s1722:"Limite de tráfego:",
    s1723:"Dias em execução:",
    s1724:"Reiniciar",
    s1725:"Hora de início do reinício:",
    s1726:"Hora de fim do reinício:",
    s1727:"(1-365)",
    s1728:"Tempo de controlo de tráfego:" ,
    s1729:"(m)",
    s1730:"(hh-mm. por exemplo, 23:34)",
    s1731:"Inserir Dias de Execução",
    s1732:":",
    s1733:"（00:00-23:59）",
    s1734:"Definição de hora",
    s1735:'Hora de início inválida.',
    s1736:'Hora de fim inválida.',
    s1737:'A hora que introduziu é inválida. Introduza um número entre 00 e 23.',
    s1738:'O minuto que introduziu é inválido. Introduza um número entre 00 e 59.',
    s1739:'O período especificado é inválido. A hora de início tem de ser anterior à hora de fim.',
    s1740:'(Kb)',
    s1741:'O tempo tem de ser um número inteiro entre 0 e 9.',
    s1742:'Para o mesmo período, a hora e o minuto de início e a hora e o minuto de fim têm de ser todos especificados ou de ficar todos em branco.',
    s1743:'Para o mesmo período, a hora de fim tem de ser posterior à hora de início.',
    s1744:'A hora de início tem de ser anterior à hora de fim.',
    s1745:'O valor de dias em execução tem de ser um número inteiro entre 1 e 365.',
    s1746:'O limite de tráfego tem de ser um número inteiro.',
    s1747:'O tempo de controlo de tráfego tem de ser um número inteiro.',
    s1748:'Nesta página, pode configurar as definições de reinício.',
    s1749:'Ignorar tráfego:',
    s1750:'O tempo de controlo de tráfego tem de ser um número inteiro de 1 a 60.',
    s1751:'O limite de tráfego tem de ser um número inteiro entre 1 e 5000.',
    s1752:'Nesta página, pode reiniciar o dispositivo manualmente ou configurar as definições de reinício automático.',
    s1753:'Reiniciar',
    s1754:'Os dados não guardados serão perdidos. Tem a certeza de que pretende reiniciar o dispositivo?',
    s1755:'A hora de fim não pode ser igual à hora de início.',
    s1756:"Hora de início:",
    s1757:"Hora de fim:",
    s1759:"Reinício manual",
    s1760:"Reinício automático",
    s1761:"(1-60Min)",
    s1762:'(1-5000KB)',
    s0d21:"Aplicar",
    s0d22:"Cancelar"
};
 
﻿var ResetLgeDes = 
{  
    s0601:    "Dados não guardados serão perdidos. Tem a certeza que pretende reiniciar o dispositivo?",
    s0602:    "Nesta página, pode reiniciar o dispositivo.",
    s0603:    "Reiniciar",
	s0604:    "Você tem certeza que deseja reiniciar o Vivo Box? \r\n Seus serviços de internet, telefonia e TV poderão ser interrompidos momentaneamente enquanto o Power Box restabelece a conexão. O processo pode levar até 5 minutos e retornará automaticamente.",
	
	s0701:	"Opções",
	s0702:	"Reiniciar",
	s0703:	"Este botão reinicia o Vivo Box. Ao clicar aqui, sua Internet, telefone e TV poderão ficar indisponíveis por alguns instantes até o termino da inicialização. Toda configuração do Vivo Box será mantida.",
	s0704:	"Reconfigurar",
	s0705:	"Este botão reconfigura o Vivo Box. Ao clicar aqui, sua Internet, telefone e TV poderão ficar indisponíveis por alguns instantes até o termino da reconfiguração. Toda personalização do Vivo Box será perdida, incluindo o nome da rede Wi-Fi e a senha, que voltarão aos valores originais.",
	s0706:	"Se restaurar as configurações predefinidas, as definições de utilizador serão perdidas após o reinício. Tem a certeza que pretende continuar?",
	s0707:	"Você tem certeza que deseja reconfigurar o Power Box? \r\n Toda a personalização será perdida, incluindo nome de rede Wi-Fi e senha.",

	s0801:	"Reiniciar",
	s0802:	"Esta página permite que reinicie a sua ligação e reinicie o seu router. Por favor, note que durante todo o processo, todos os serviços de telefone, Internet e TV estarão temporariamente indisponíveis.",
	s0803:	"Clique aqui para reiniciar o seu Vodafone Smart Router.",
    s0804:	"Tem certeza que deseja reiniciar o seu Vodafone Smart Router?",
    s0805:	"Confirmar",
    s0806:	"Cancelar",
    s0807:	"Reiniciar em progresso",
    s0808:	"Não desligue o seu Vodafone Smart Router."
}; 
﻿var RestoreLgeDes = 
{
    s0a01:    "Se restaurar as configurações predefinidas, as definições de utilizador serão perdidas após o reinício. Tem a certeza que pretende continuar?",
    s0a02:    "Nesta página, pode restaurar as configurações predefinidas.",
    s0a03:    "Predefinição",
	s0a04:	  "Quer reiniciar configurações IoT? Se sim, tem de reinstalar sensores um por um.",
	s0a05:	  "Reiniciar configurações IoT",
	s0a06:	  "Aplicar",
	s0a07:	  "Cancelar",
	s0a00:"Se restaurar configurações do ficheiro de backup, as configurações atuais serão perdidas e o dispositivo reiniciará automaticamente. Tem a certeza de que pretende restaurar?",
	s0aa0:"Restaurar configuração",
	s0aa1:"Selecionar ficheiro de backup de configuração:",
	s0aa2:"Restaurar configuração"
};
 
﻿var SambaLgeDes =
{
	ss1116b:    "1. Recomenda-se que a palavra-passe apenas contenha 6 caracteres.<br/>2. É recomendado que sejam adicionados pelo menos dois tipos dos seguintes caracteres sejam incluídos na palavra-passse: números, letras maiúsculas e minúsculas e caracteres especiais. Os caracteres especiais podem ser os seguintes:`~!@#$%^&*()-_=+|[{}];:'&lt;,.&gt;/?<br/>3. É recomendado que a palavra-passe não seja o nome do utilizador ou o nome do utilizador de trás para a frente.",
	ss1116c:    "1. Recomenda-se que a palavra-passe apenas contenha 6 caracteres.<br/>2. É recomendado que sejam adicionados pelo menos dois tipos dos seguintes caracteres sejam incluídos na palavra-passse: números, letras maiúsculas e minúsculas e sublinhados (_).<br/>3. É recomendado que a palavra-passe não seja o nome do utilizador ou o nome do utilizador de trás para a frente.",
	s0526:      "Aplicar",
	s0527:      "Cancelar",
	s0531:      "Atenção:",
	s0532:      "Não remova e volte a inserir o dispositivo de armazenamento USB em utilização. Esta acção poderá danificar os ficheiros do dispositivo.",
	s1400:      "Nesta página, pode ativar a sua impressora e a partilha de armazenamento.<br/>Para o fazer, ligue a impressora à router através de uma porta USB. A impressora e a router partilham um endereço IP. Procure pela impressora e instale o controlador. Após isso, já pode usar a impressora.",
	s1401:      "Ativar autenticação de impressora e armazenamento:",
	s1402:      "Informação da impressora:",
	s1403:      "Ativar autenticação:",
	s1404:      "Definições de conta",
	s1405:      "Detalhes",
	s1406:      "Nome de utilizador:",
	s1407:      "Palavra-passe:",
	s1408:      "Ativar :",
	s1409:      "Permissão:",
	s1410:      "Partilhar diretório :",
	s1411:      "Diretório :",
	s1412:      "Tem a certeza que pretende apagar o utilizador?",
	s1413:      "ID",
	s1414:      "Nome de utilizador",
	s1415:      "Estado",
	s1416:      "Permissão",
	s1417:      "Diretório partilhado",
	s1418:      "Ativar",
	s1419:      "Desativar",
	s1420:      "Só de leitura",
	s1421:      "Leitura e escrita",
	s1422:      "Ocultar",
	s1423:      "Todos os diretórios",
	s1424:      "Especifique diretório",
	s1425:      "Procurar",
	s1426:      " O nome de utilizador não pode estar em branco. Tente novamente.",
	s1427:      "O nome de utilizador não pode ser um nome especial ou nome de processo utilizado pelo sistema. Tente novamente.",
	s1428:      "O nome de utilizador jã existe. Tente novamente.",
	s1429:      "Nome de utilizador inválido. O nome de utilizador pode conter apenas minúsculas, dígitos e traço inferior.",
	s1430:      "O palavra-passe não pode estar em branco. Tente novamente.",
	s1431:      "O diretório do serviço de armazenamento do utilizador não pode estar em branco.",
	s1432:      "Pode ser configurado até um máximo de 8 utilizadores.",
	s1433:      "Dispositivos de armazenamento USB:",
	s1434:      "Anterior",
	s1435:      "OK",
	s1436:      "Procurar diretório",
	s1437:      "Palavra-passe inválida. Tente novamente.",
	s1438:      "O nome de utilizador não pode começar com um dígito. Tente novamente.",
	s1439:      "A palavra-passe é fraca. Continuar?",
	s1440:      "A palavra-passe contém apenas letras, dígitos e underscores (_).",
	s1441:      "O comprimento do diretório ultrapassa o limite",
	s1442:      "A palavra-passe é fraca. Introduza novamente a palavra-passe.",
	s1443:      "Falhou ao obter a ID de partição do disco lógico. Atualize a página e tente de novo.",
	s1444:      "Partilha doméstica USB",
	s1445:      "Partilha",
	
	s0557:  	"Força da senha:",
    s0558:  	"Fraca",
    s0559:  	"Média",
    s0560:  	"Forte",	
	s1078:      "O serviço ativado utiliza protocolos inseguros. É aconselhado ter o serviço desativado por predefinição",
	
	s1079:		"Ativar Print Sharing",
	s1080:		"Nome da impressora",
	s1081:		"Printer Sharing",
	s1082:		"Pode partilhar a sua impressora com outros utilizadores da rede local",
	s1083:		"Lembre-se que este serviço está desativo por default. Recomendamos que, por motivos de segurança, desative esses serviços quando não os usar.",

	s2001:		"Network Share (Samba)",
	s2002:		"Pode partilhar o conteúdo de equipamentos USB conectados em sua rede usando partilhas de rede (Samba).",
	s2003:		"Lembre-se que este serviço está desativado por default. Recomendamos que, por motivos de segurança, desative esses serviços quando não os usar",
	s2004:		"ADATA USB Flash Drive",
	s2005:		"Requer nome de utilizador e password",
	s2006:		"Nome de utilizador",
	s2007:		"Password atual",
	s2008:		"Samba Server IP Address",
	s2009:		"Partilhar todas as pastas",
	s2010:		"Mostrar caracteres",
	s2011:		'Nome de utilizador inválido. Não são permitidos nomes de utilizador comuns.',
	prin005:		'Diretório especificado'
};

var content_language = {
	content001:		'Content Sharing',
	content002:		'Pode partilhar o conteúdo de equipamentos USB conectados e torná-lo acessível a outros utilizadores na sua rede local.',
	content003:		'Lembre-se que este serviço está desativo por default. Recomendamos que, por motivos de segurança, desative esses serviços quando não os usar',
	content004:		'Ativar content Sharing'
};

var printer_language = {
	prin001:		'Ativar Print Sharing',
	prin002:		'Nome da impressora',
	prin003:		'Pode partilhar a sua impressora com outros utilizadores da rede local',
	prin004:		'Lembre-se que este serviço está desativo por default. Recomendamos que, por motivos de segurança, desative esses serviços quando não os usar.'
}; 
﻿var SmartOntdes =
{
	smart001:"Informação PON",
	smart001_xd:"Informação DSL",	
	smart002:"Estado de ligação:",
	smart003:"Ligado",
	smart004:"Desligado",
	smart005:"Duração de ligação:",
	smart006:"h",
	smart007:"min",
	smart008:"s",
	smart009:"Estado de registo do gateway",
	smart010:"Directório óptico (OLT):",
	smart011:"Não autenticado",
	smart012:"Autenticação com sucesso",
	smart013:"Falha na autenticação",
	smart014:"Estado de registo (ACS):",
	smart015:"Não registado",
	smart016:"Registo concluído",
	smart017:"Falha no registo",
	smart018:"Estado de ligação à rede",
	smart019:"Protocolo IP:",
	smart020:"Endereço IP:",
	smart021:"Protocolo Linha:",
	smart022:"Com êxito",
	smart023:"Não reportado",
	smart024:"Sem resposta",
	smart025:"Interrompido",
	smart026:"Desconhecido",
	smart027:"Endereço IPv4:",
	smart028:"Endereço IPv6:",
	smart029:"A fibra está desligada.",
	
	s0702:    "O diretório  do ficheiro não pode ficar em branco.",
	s0703:    "O comprimento do diretório  não pode exceder 128 carateres .",
	s0905:    "O sistema está ocupado. Tente novamente mais tarde.",
	s1118:    '<strong class="color_red1">A palavra-passe de início de sessão é a predefinida. Mude-a já.</strong>',
	s1119:    "A recolher a informação sobre a falha... Aguarde.",
	s1120:	  "Plugin",
	s1121:    "CPU",
	s1122:    "Thread",
	s1123:    "Memória",
	s1124:    "Socket",
	s1125:    "Armazenamento",
	s1126:    "Monitorização de recursos JVM",
	s1127:    "Aqui, pode consultar as informações de monitorização de recursos JVM e visualizar registos. Em alternativa, pode clicar em Transferir Registos para transferir os ficheiros de registo.",
	s1128:    "Transferir ficheiro de registo",
	s1129:    "Atualizar",
	s1130:    "Transferir e Ver registos",
	s1131:	  "O sistema JVM está funcionando corretamente e não há alarmes."
};
 
﻿var SntpLgeDes =
{
    s0c01: "O período de sincronização da hora deve ser superior a 0.",
    s0c02: "Período de sincronização da hora inválido.",
    s0c03: "A segunda caixa de texto do servidor SNTP primário não pode estar em branco quando outro está selecionado na primeira caixa de texto.",
    s0c04: "Formato do endereço IP do servidor SNTP primário inválido.",
    s0c05: "Endereço IP do servidor SNTP primário inválido. Introduza um endereço de difusão singular.",
    s0c06: "Endereço do servidor SNTP primário inválido.",
    s0c07: "A segunda caixa de texto do servidor SNTP secundário não pode estar em branco quando outro está selecionado na primeira caixa de texto.",
    s0c08: "Formato do endereço IP do servidor SNTP secundário inválido.",
    s0c09: "Endereço IP do servidor SNTP secundário inválido. Introduza um endereço de difusão singular.",
    s0c0a: "Endereço do servidor SNTP secundário inválido.",
    s0c0b: "Alterações no fuso horário apenas têm efeito após a reinicialização.",
    s0c0c: "Definições DST não podem estar vazias.",
    s0c0d: "Formato de hora incorreto.",
    s0c0e: "O início e fim têm de ser especificados.",
    s0c0f: "Nesta página, pode configurar o protocolo SNTP, fuso horário e DST para obter a hora exata.",
    s0c10: "Sincroniza automaticamente com o servidor de hora da rede.",
    s0c11: "Servidor SNTP primário:",
    s0c12: "Servidor SNTP secundário:",
    s0c13: "Fuso horário:",
    s0c14: "Período de Sincronização de Hora:",
    s0c15: "(s)",
    s0c16: "Nome da WAN:",
    s0c17: "Aplicar",
    s0c18: "Cancelar",
    s0c19: "Ativar DST",
    s0c1a: "Hora de início DST:",
    s0c1b: "janeiro ",
    s0c1c: "fevereiro ",
    s0c1d: "março ",
    s0c1e: "abril ",
    s0c1f: "maio ",
    s0c20: "junho ",
    s0c21: "julho ",
    s0c22: "agosto ",
    s0c23: "setembro ",
    s0c24: "outubro ",
    s0c25: "novembro ",
    s0c26: "dezembro ",
    s0c27: "Primeiro",
    s0c28: "Segundo",
    s0c29: "Terceiro",
    s0c2a: "Quarto",
    s0c2b: "Último",
    s0c2c: "Domingo",
    s0c2d: "Segunda-feira",
    s0c2e: "Terça-feira",
    s0c2f: "Quarta-feira",
    s0c30: "Quinta-feira",
    s0c31: "Sexta-feira",
    s0c32: "Sábado",
    s0c33: "Hora:",
    s0c34: "",
    s0c35: "Minuto:",
    s0c36: "",
    s0c37: "Segundo:",
    s0c38: "",
    s0c39: "Hora de fim DST:",
	s0c40: "Hora atual:",
	s0c41: "As datas de início e fim DST não podem ser no mesmo mês.",
	s0c42: "Validar predefinição de período de tempo",
	s0c43: "Dia",
	s0c44: "Período de tempo",
	s0c45: "Indicador global a desativar período de tempo",
	s0c46: "Sim",
	s0c47: "Indicador a desativar predefinição período de tempo",
	s0c48: "Desativar o indicador",
	s0c49: "Definição de tempo",
	s0c54: "Aviso:",
	s0c55: "Configurações incorretas podem afetar os serviços relacionados com a hora. Por este motivo, é aconselhável manter as predefinições de fábrica."
};

var snt_language ={
	snt001:			'NTP',
	snt002:			'Definições NTP',
	snt003:			'Sincronizar com o servidor NTP',
	snt004:			'Fuso horário',
	snt005:			'Período de atualização',
	snt006:			'Intervalo de repetição',
	snt007:			'Primeiro servidor NTP',
	snt008:			'Segundo servidor NTP',
	snt009:			'Terceiro Servidor NTP',
	snt010:			'Quarto servidor NTP',
    snt011:			'Quinto Servidor NTP',
    snt012:			'Período de sincronização horária inválido',
    snt013:			'Intervalo de repetição de tempo inválido',
    snt014:			'Mês',
    snt015:			'semana',
    snt016:			'Dia da semana',
    snt017:			'Hora',
    snt018:			'Minuto',
    snt019:			'Segundo',
    snt020:			'Hora de início DST',
    snt021:			'Hora de fim DST',
    snt022:			'Configuração do DTS'
} 
﻿var SoftNoticeDes = 
{ 
	s2001:    "Nesta página, veja a informação do software de código aberto do dispositivo.",
	s2002:    "AVISO DE SOFTWARE DE FONTE ABERTA",
	s2003:    "Este documento contém um aviso de software de código aberto para este produto. As licenças de software de código aberto são concedidas pelos respetivos proprietários dos direitos. As licenças de código aberto prevalecem sobre todas as outras informações de licença relacionadas com o respetivo software de código aberto contido no produto.",
	s2004:    "Isenção de Garantia",
	s2005:    "O SOFTWARE DE CÓDIGO DE ABERTO EXISTENTE NESTE PRODUTO É DISTRIBUÍDO TENDO EM VISTA A SUA UTILIDADE, MAS SEM QUALQUER GARANTIA, INCLUSIVE SEM A GARANTIA IMPLÍCITA DE COMERCIABILIDADE OU ADEQUAÇÃO A FINS ESPECÍFICOS. PARA MAIS INFORMAÇÕES, CONSULTE AS LICENÇAS APLICÁVEIS.",
	s2006:    "Informação de Software de Fonte Aberta",
	s2007:    "Software",
	s2008:    "Versão",
	s2009:    "Aviso de Direitos de autor",
	s2010:    "Licença",
	s2011:    "Hiperligação da Licença",
	s2012:    "Proposta por escrito",
	s2013:    "Este produto contém software para o qual os proprietários dos direitos concedem uma licença nos termos da Licença Pública Geral GNU, versão 2 (GPLv2) e/ou outras licenças de software de código aberto. A si e a quaisquer terceiros, iremos fornecer o código-fonte do software ao abrigo de uma licença de software de código aberto. Basta enviar-nos um pedido por escrito, por correio ou e-mail, para os seguintes endereços:<br/>foss@huawei.com<br/>Indique o nome do produto e a versão de firmware para a qual necessita do código-fonte, e indique também o seu contacto.<br/><br/><span class=copyrightinfo_title_bold>TENHA EM ATENÇÃO QUE IREMOS SOLICITAR QUE PAGUE OS CUSTOS DE TRANSPORTE E OS ENCARGOS POSTAIS DO ENVIO PARA SI. ESTA PROPOSTA É VÁLIDA DURANTE TRÊS ANOS A PARTIR DA DATA DE DISTRIBUIÇÃO DO PRODUTO E ENQUANTO TIVERMOS DISPONIBILIDADE DE PEÇAS SOBRESSELENTES OU DE APOIO AO CLIENTE PARA ESSE MODELO DE PRODUTO.</span>",
	s2014:    "Aviso de Software de Fonte Aberta",
	s2050:    "Textos de aviso de direitos de autor e licença"
};
 
﻿var WebcertmgntLgeDes = 
{ 	
	s0d21:    "Aplicar",
    s0d22:    "Cancelar",
    s0d23:    "Ativar certificado de autenticação e definir palavra-passe de chave privada",
    s0d25:    "Ativar certificado de autenticação:",
    s0d26:    "Palavra-passe de chave privada:",
    s0d28:    "Confirmar palavra-passe:",
    s0d29:    "Importar certificado",
    s0d2a:    "Certificado:",
    s0d2b:    "Procurar",
    s0d2c:    "Importar certificado",
	s0d10:    "Selecione  um diretório  de ficheiro.",
    s0d11:    "O comprimento do diretório  de ficheiro não pode exceder 128 carateres.",
	s0d0f:    "A palavra-passe confirmada é diferente da palavra-passe de chave privada.",
	s0d14:    "Palavra-passe de chave privada alterada com sucesso. Tem efeito após reiniciar o dispositivo.",
	s1430:		"O palavra-passe não pode estar em branco. Tente novamente.",
	s1116:    "1.A palavra-passe deve conter pelo menos 6 carateres.</br>2. A palavra-passe deve conter pelo menos duas das seguintes combinações: Digit, maiúsculas, minúsculas </br>&nbsp;&nbsp;&nbsp;Carateres especiais (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ? e espaços).</br>3.A palavra-passe não pode conter o nome de utilizador nem de forma alterada ou revertida.",
	s1901:	  'Nesta página, pode definir a palavra-passe de autenticação SSL utilizada para aceder ao ONT utilizando HTTPS e importar o certificado SSL correspondente.',
	s1902:	  'A palavra-passe é demasiado fraca. Configure novamente.',
	s1903:	  'Gestão de Certificado SSL',
	s1904:    "A palavra-passe deve conter entre 1 a 127 carateres .",
	s1905:    "(1-127 carateres. A palavra-passe tem efeito após a reiniciar o dispositivo.)"
};
 
﻿var testspeed_language = 
{
	speed_menu:					'Teste de velocidade da rede doméstica',
	speed_menu2:				'Teste de velocidade da rede',
	speed_title:				'Nesta página, pode utilizar a funcionalidade de teste de velocidade da rede doméstica para verificar o estado da largura de banda da rede atual.',
	speed_title2:				'Nesta página, pode utilizar a funcionalidade de teste de velocidade da rede para verificar o estado da largura de banda da rede atual.',
	web_speedurl:				'URL de destino:',
	web_choosewan:				'Nome da WAN:',
	web_account:				'Conta PPPoE:',
	web_password:				'Palavra-passe PPPoE:',
	web_Upload:					'Modo:',
	web_advanceconfig:			'Definições avançadas',
	web_threads:				'Tarefas em simultâneo:',
	web_speedtime:				'Duração:',
	web_apply:					'Iniciar',
	web_cancel:					'Parar',
	web_speedresult:			'Resultado do teste',
	web_result:					'Resultado',
	web_numb1:					'1',
	web_numb2:					'2',
	web_numb3:					'3',
	web_numb4:					'4',
	web_time0:					'0',
	web_time10:					'10s',
	web_time20:					'20s',
	web_time30:					'30s',
	web_time40:					'40s',
	web_time50:					'50s',
	web_time60:					'60s',
	web_upload:					'Carregar',
	web_download:				'Transferir',
	web_Attributes:				'Atribuir',
	web_upspeeding:				'A testar a velocidade de carregamento...',
	web_downspeeding:			'A testar a velocidade de transferência...',
	web_value:				    'Resultado',
	web_romtime:				'Tempo ROM:',
	web_bomtime:  				'Tempo BOM:',
	web_eomtime:				'Tempo EOM:',
	web_testbytes:				'Bytes de teste recebidos:',
	web_totalrecevied:			'Total de bytes recebidos:',
	web_tcpopenresq:			'Hora do pedido de abertura do TCP:',
	web_tcpopenresp:			'Hora da resposta de abertura do TCP:',
	web_totalsent:				'Total de bytes enviados:',
	web_testreceload:			'Bytes de teste recebidos com carga completa:',
	web_testsentload:			'Bytes de teste enviados com carga completa:',
	web_totalrece:				'Total de bytes recebidos com carga completa:',
	web_totalsentload:			'Total de bytes enviados com carga completa:',
	web_perload:				'Período de carga completa:',
	web_pernumber:				'Número de entradas do resultado por ligação:',
	web_increment:				'Número de entrada do resultado incremental:',	
	web_downdiagresult:			'Resultado incremental máximo do diagnóstico de transferências:',
	web_downdiagconnect:		'Ligações máximas do diagnóstico de transferências:',
	web_uploaddiagresult:		'Resultado incremental máximo do diagnóstico de carregamentos:',
	web_uploaddiagconnect:		'Ligações máximas do diagnóstico de carregamentos:',	
	web_ipaddused:				'Endereço IP utilizado:',
	web_uploadsport:			'Protocolo de diagnóstico:',
	web_downloadsport:			'Protocolo de diagnóstico:',
	web_protocol:				'Introduza o número de protocolo correto.',
	web_errorurl:				'Introduza o URL de destino correto.',
	web_sampvalue:				'Valor de amostra:',
	web_sampvaluetitle:			'Valor de amostra',
	web_status:					'Estado:',
	web_erroraccount:			'A palavra-passe ou conta PPPoE está em branco.',
	web_mark:					'0 indica que a duração do teste de velocidade é calculada no final da transferência com o tamanho real do ficheiro.'
};
 
﻿var Tr069LgeDes = 
{
    s0100:    "Nesta página, é possível definir parâmetros ACS, definir a palavra-passe de autenticação utilizando um certificado SSL e importar o certificado SSL necessário.",
    s0100_ap: "Nesta página, você pode definir os parâmetros ACS, função de mapeamento de porta do gateway principal, definir a senha de autenticação do certificado SSL e importar o certificado SSL correspondente.",
	s0101:    "Configuração ACS",
	s1116:    "1.A palavra-passe deve conter pelo menos 6 carateres.<br/>2. A palavra-passe deve conter pelo menos duas das seguintes combinações: Digit, maiúsculas, minúsculas <br/>&nbsp;&nbsp;&nbsp;Carateres especiais (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ? e espaços).<br/>3.A palavra-passe não pode conter o nome de utilizador nem de forma alterada ou revertida.",
	s1430:		"O palavra-passe não pode estar em branco. Tente novamente.", 
	s1902:	  'A palavra-passe é demasiado fraca. Configure novamente.',
    s0d01:    "Introduza um URL.",
    s0d02:    "O URL dos ACS não podem conter espaços ou os seguintes símbolos:\"< > \' \" { } [ ] % \\ ^ # |\"",
	s0d02Ex:    "O URL dos ACS não podem conter espaços ou os seguintes símbolos:\"< > \' \" { } % \\ ^ # |\"",
    s0d03:    "Intervalo de notificação inválido.",
    s0d04:    "Período de notificação inválido.",
    s0d05:    "Introduza um nome de utilizador ACS.",
    s0d06:    "Nome de utilizador ACS inválido.",
    s0d07:    "Introduza a palavra-passe ACS.",
    s0d08:    "Palavra-passe ACS inválida.",
    s0d09:    "Introduza um nome de utilizador de solicitação de ligação.",
    s0d0a:    "Nome de utilizador de solicitação de ligação inválido.",
    s0d0b:    "Introduza uma palavra-passe de solicitação de ligação",
    s0d0c:    "Palavra-passe de solicitação de ligação inválida",
    s0d0d:    "Valor DSCP inválido.",
    s0d0e:    "A palavra-passe deve conter entre 1 a 32 carateres.",
    s0d0f:    "A palavra-passe confirmada é diferente da palavra-passe de chave privada.",
    s0d10:    "Selecione  um diretório  de ficheiro.",
    s0d11:    "O comprimento do diretório  de ficheiro não pode exceder 128 carateres.",
    s0d12:    "O ficheiro é demasiado grande.",
    s0d13:    "inválido ou inexistente.",
    s0d14:    "Palavra-passe de chave privada alterada com sucesso. Tem efeito após reiniciar o dispositivo.",
    s0d15:    "Definições de parâmetros ACS",
    s0d16:    "Se a ligação automática TR069 estiver ativada, poderá definir os parâmetros ACS do terminal.",
    s0d17:    "Ativar  Notificação Periódica:",
    s0d18:    "Intervalo de Notificação:",
    s0d19:    "Hora de Notificação:",
    s0d1a:    "dd-mm-aaaaHhh:mm:ss (por exemplo, 20-12-2009H12:23:34)",
    s0d1b:    "Nome de utilizador do ACS:",
    s0d1c:    "Palavra-passe ACS:",
    s0d1d:    "(1-256 carateres)",
    s0d1e:    "Nome de utilizador da notificação de ligação:",
    s0d1f:    "Palavra-passe da notificação de ligação:",
    s0d20:    "(1-256 carateres)",
    s0d21:    "Aplicar",
    s0d22:    "Cancelar",
    s0d23:    "Ativar certificado de autenticação e definir palavra-passe de chave privada",
    s0d24:    "Para permitir que o dispositivo se ligue ao ACS em modo SSL, terá que ativar  o certificado de autenticação, definir a palavra-passe de chave privada e importar o certificado fornecido pelo portador.",
    s0d25:    "Ativar certificado de autenticação:",
    s0d26:    "Palavra-passe de chave privada:",
    s0d27:    "(1-32 carateres. A palavra-passe tem efeito após a reiniciar o dispositivo.)",
    s0d28:    "Confirmar palavra-passe:",
    s0d29:    "Importar certificado",
    s0d2a:    "Certificado:",
    s0d2b:    "Procurar",
    s0d2c:    "Importar certificado",
	s0d2d:    "O URL do ACS tem um ID da porta inválido.",
	s0d2e:    "O URL do ACS contém carateres não ACSII.",
	s0d2f:    "URL do ACS:",
	s0d30:    "DSCP:",
	s0d31:    "A palavra-passe ACS é muito fraca. Tem a certeza que pretende continuar?",
	s0d32:    "A palavra-passe do pedido de ligação é muito fraca. Tem a certeza que pretende continuar?",
	s0d33:    "A palavra-passe do ACS e do pedido de ligação são muito fracas. Tem a certeza que pretende continuar?",
	s0d34:"[1 - 2147483647](s)",
	s0d35:"(0~63)",
    s0d36:"Ativar gestão ACS:",
    
    s1800:"Configuração do cliente TR-069",
	s1801:"Informar",
	s1802:"Informar intervalo",
	s1803:"singleinput",
	s1804:"URL do ACS",
	s1805:"Nome de utilizador do ACS",
	s1806:"Password do ACS",
	s1807:"Nome de utilizador do pedido de ligação",
	s1808:"Connection Request Password",
	s1809:"Certificado TR-069",
	s1810:"Carregue o certificado TR-069",
	s1811:"Certificado:",
    s1812:"Selecione o ficheiro",
    s1813:"Nenhum arquivo selecionado.",
    s1813:"O ficheiro seleccionado não é uma actualização válida.",
    s0e05:"Configuração automática da porta de gateway principalMapping",
	s0e06:"Habilitar:",
	s0e07:"Porta externa:",
	s0e08:"A configuração automática só entra em vigor após o sistema ser reiniciado.Tem certeza de que deseja enviar e reiniciar o sistema?"
};
 
﻿var UsbBackupLgeDes =
{
	s052e: "Nenhum dispositivo USB",
	s0531: "Atenção:",
	s0532: "Não remova e volte a inserir o dispositivo de armazenamento USB em utilização. Esta acção poderá danificar os ficheiros do dispositivo.",
	s0801: "Selecione  um dispositivo USB.",
	s0802: "O ficheiro de configuração já existe. Tem a certeza que pretende substituir?",
	s0803: "Nesta página, pode fazer cópias de segurança dos ficheiros de configuração para o dispositivo USB ou restaurar os ficheiros do dispositivo.",
	s0804: "Restauração rápida",
	s0805: "Ativar  recuperação do USB:",
	s0806: "Aplicar",
	s0807: "Cancelar",
	s0808: "Configuração de cópia de segurança USB",
	s0809: "Dispositivo USB:",
	s080a: "Cópia de segurança do ficheiro de configuração",
	s080b: "Substituir Ficheiro Antigo:"
};
 
﻿var UsbstatusLgeDes =
{
	s0401:"Nesta página, pode ver o estado do dispositivo USB.",
	s0402:"Estado USB:",
	s0403:"Desligado",
	s0404:"Ligado",
	s0405:"Estado USB"
};
 
﻿var UsbHostLgeDes =
{
	s1436:    "Procurar diretório",
	s1439:    "A palavra-passe é fraca. Continuar?",
	s1605:    "Procurar",
	ss1116b:  "1. Recomenda-se que a palavra-passe apenas contenha 6 caracteres.<br/>2. É recomendado que sejam adicionados pelo menos dois tipos dos seguintes caracteres sejam incluídos na palavra-passse: números, letras maiúsculas e minúsculas e caracteres especiais. Os caracteres especiais podem ser os seguintes:`~!@#$%^&*()-_=+|[{}];:'&lt;,.&gt;/?<br/>3. É recomendado que a palavra-passe não seja o nome do utilizador ou o nome do utilizador de trás para a frente.",
	s0501:    "Identificação de porta inválida.",
	s0502:    "ID da porta inválida. Introduza um número situado entre 1 e 65535.",
	s0503:    "Excedeu o comprimento limite do nome de utilizador (255 carateres ).",
	s0504:    "Introduza um nome de utilizador válido.",
	s0505:    "O nome de utilizador não pode conter espaços.",
	s0506:    "A palavra-passe é demasiado longa.",
	s0506b:   "(1-20 carateres)",
	s0507:    "Palavra-passe inválida.",
	s0508:    "O caminho é demasiado comprido.",
	s0509:    "Caminho inválido.",
	s050a:    "URL do FTP inválido.",
	s050b:    "O URL do FTP não pode conter espaços ou os seguintes símbolos:\"< > \' \" { } [ ] % \\ ^ # |\"",
	s050c:    "Selecione  um dispositivo USB.",
	s050d:    "Excedeu o comprimento limite do nome de utilizador (256 carateres ).",
	s050e:    "Introduza o nome de utilizador.",
	s050f:    "Nome de utilizador inválido.",
	s0510:    "Nome de utilizador inválido.",
	s0511:    "Excedeu o comprimento limite da palavra-passe (256 carateres ).",
	s0512:    "A palavra-passe não pode ficar em branco.",
	s0513:    "Palavra-passe inválida.",
	s0514:    "Selecione  um dispositivo USB.",
	s0515:    "Excedeu o comprimento limite do diretório  raiz (256 carateres ).",
	s0516:    "Diretório  raiz inválido.",
	s0517:    "O servidor FTP irá reiniciar de alterar as configurações. Tem a certeza que pretende continuar?",
	s0518:    "Configuração do Cliente FTP",
	s0519:    "Nesta página, pode configurar o cliente FTP para transferir ficheiros da rede para um dispositivo USB.",
	s051a:    "ID da porta:",
	s051b:    "Nome de utilizador:",
	s051c:    "Palavra-passe:",
	s051d:    "Dispositivo USB:",
	s051e:    "Diretório :",
	s051f:    "Transferir",
	s0520:    "Estado",
	s0521:    "Configuração do Servidor FTP",
	s0522:    "Nesta página, pode configurar o servidor FTP para partilhar dados num dispositivo USB com dispositivos na LAN.",
	s0523:    "Ativar  o acesso LAN administrada ou WAN administrada através da função FTP. Em seguida, selecione  o modo UTF-8.",
	s0524:    "Ativar  o servidor FTP:",
	s0525:    "Diretório  raiz:",
	s0526:    "Aplicar",
	s0527:    "Cancelar",
	s0528:    "Nome de utilizador",
	s0529:    "Palavra-passe",
	s052a:    "ID da porta",
	s052b:    "Diretório ",
	s052c:    "A palavra-passe não pode começar com um espaço.",
	s052d:    "A palavra-passe não pode terminar com um espaço.",
	s052e:    "Nenhum dispositivo USB",
	s052f:    "FTP URL:",
	s0530:    "FTP URL",
	s0531:    "Atenção:",
	s0532:    "Não remova e volte a inserir o dispositivo de armazenamento USB em utilização. Esta acção poderá danificar os ficheiros do dispositivo.",
	s0533:    "Este ficheiro já existe no dispositivo de armazenamento USB. Tem a certeza que pretende substituí-lo?",
	s0534:    "O endereço URL FTP não pode conter os seguintes carateres: \"<, >, \', \", {, }, [, ], \\, ^, #, |\".",
	s0535:    "(/example: test/test.txt)",
	s0536:    "Nesta página, é possível configurar o cliente FTP para transferência de ficheiro a partir de um dispositivo de armazenamento de um gateway doméstico e configurar o servidor FTP para partilha de recursos.",
	s0537:    "<strong class=\"color_red\">Ao configurar o servidor FTP, active a função FTP  LAN-side ou WAN-side e seleccione o código caracter em formato UTF-8.</strong>",
	s0538:    "Configuração FTP",
	s0539:    "Nesta página, é possível configurar o cliente FTP para transferência de ficheiro a partir de um dispositivo de armazenamento de um gateway doméstico e configurar o servidor FTP para partilha de recursos.<br> Ao configurar o servidor FTP, active a função FTP  LAN-side ou WAN-side e seleccione o código caracter em formato UTF-8.<br>Atenção:<br>Não remova e volte a inserir o dispositivo de armazenamento USB em utilização. Esta acção poderá danificar os ficheiros do dispositivo.",
	s0540:	  "O dispositivo USB encontra-se em modo de leitura e não permite a escrita de dados.",
	s0541:	  "O cartão SD encontra-se em modo de leitura e não permite a escrita de dados. ",
	s0542:	  "O dispositivo de armazenamento encontra-se em modo de leitura e não permite a escrita de dados.",
	s0543:    "A porta configurada está em conflito com a porta de serviço interna.",
	s0544:    "A porta configurada está em conflito com a porta do serviço de mapeamento de portas.",
	s0545:    "A porta configurada está em conflito com a porta do serviço de disparo de portas.",
	s0546:    "A porta configurada está em conflito com a porta de serviço de voz.",
	s0547:    "A porta configurada está em conflito com a porta de serviço FTP.",
	
	s0549:    "Nesta página pode remover os dispositivos USB ligados.",
	s0550:    "Remover dispositivos USB",
	s0551:    "Remover",
	s0552:    "Atualizar",
	s0553:    "Tem a certeza de que pretende remover o dispositivo?",
	s0554:    "O dispositivo USB selecionado não está ligado ou foi removido.",
	s0555:    "O dispositivo USB removido só pode ser identificado depois de removido e inserido novamente.<br>Poderão perder-se dados se o dispositivo USB a remover contiver dados em leitura ou escrita.",
	s0556:    "Remover dispositivos USB",
	
	s0557:  "Força da senha:",
	s0558:  "Fraca",
    s0559:  "Média",
    s0560:  "Forte",
	s0561:	"O serviço ativado utiliza protocolos inseguros. É aconselhado ter o serviço desativado por predefinição",
	
	s0599sftp:    "Configuração FTP/SFTP",
	s0600sftp:    "Nesta página, você pode configurar o cliente FTP/SFTP para baixar o arquivo do dispositivo de armazenamento do gateway principal, além de configurar o servidor FTP/SFTP para compartilhar o recurso. <br> Ao configurar o servidor FTP/SFTP, ative a função FTP/SFTP da LAN lateral ou da WAN lateral e selecione o código do caractere no formato UTF-8.<br>Atenção:<br>não remova ou insira novamente o dispositivo de armazenamento USB em uso, pois isso pode danificar os arquivos inseridos nele.",
	s0601sftp:    "Tipo do servidor FTP/SFTP",
	s0602sftp:    "Tipo de servidor:",
	s0603sftp:    "Configuração do cliente SFTP",
	s0604sftp:    "Nome de usuário:",
	s0605sftp:    "Senha:",
	s0606sftp:    "Confirmar senha:",
	s0607sftp:    "Modo do diretório:",
	s0608sftp:    "Todos os diretórios",
	s0609sftp:    "Escolher diretório",
	s0610sftp:    "Privilégio:",
	s0611sftp:    "Somente leitura",
	s0612sftp:    "Leitura e gravação",
	s0613sftp:    "Ativar conta:",
	s0614sftp:    "Nome de usuário",
	s0615sftp:    "Senha",
	s0616sftp:    "Modo do diretório",
	s0617sftp:    "Privilégio",
	s0618sftp:    "Ativar conta",
	s0619sftp:    "Configuração do servidor SFTP",
	s0620sftp:    "Ativar servidor SFTP:",
	s0621sftp:    "Modo:",
	s0622sftp:    "Ativar LAN",
	s0623sftp:    "Ativar WAN",
	s0624sftp:    "ID da porta:",
	s0625sftp:    "Clique para vincular os serviços SFTP e SSH a uma porta personalizada",
	s0626sftp:    "Período máximo ocioso:",
	s0627sftp:    "Clique para ativar o período automático de desconexão",
	s0628sftp:    "segundos (60 min)",
	s0629sftp:    "Status do serviço SFTP:",
	s0630sftp:    "Duração máxima da WAN:",
	s0631sftp:    "Período on-line do SFTP:",
	s0632sftp:    "Aplicar",
	s0633sftp:    "Cancelar",
	s0634sftp:    "Aplicar",
	s0635sftp:    "Cancelar",
	s0636sftp:    "Procurar...",
	s0637sftp:    "Procurar diretório",
	s0638sftp:    "Configuração inválida.",
	s0639sftp:    "Enable SFTP user:",
	s0640sftp:    "Enable SFTP user",
	s0641sftp:    "1.Há riscos de segurança. <br> 2.Se o serviço não estiver em uso, desative-o.",
	s0642sftp:    "Editar",
	s0643sftp:    "Nome de usuário:",
	s0644sftp:    "Old Password:",
	s0645sftp:    "Nova senha:",
	s0646sftp:    "Confirmar senha:",
	s0647sftp:    "1.A senha deve conter pelo menos seis caracteres.<br/>2.A senha deve conter pelo menos duas das seguintes combinações: <br/>&nbsp;&nbsp;&nbsp;Dígito, letra maiúscula, letra minúscula <br/>&nbsp;&nbsp;&nbsp;e caracteres especiais (` ~ ! @ # $ % ^ & * ( ) - _ = + \\ | [ { } ] ; : ' \" < , . > / ?).<br/>3. A senha não pode ser um nome de usuário ou o nome de usuário ao contrário.",
	s0648sftp:    "Aplicar",
	s0649sftp:    "Cancelar",
	s0650sftp:    "A senha de confirmação é diferente da nova senha.",	
	s0651sftp:    "A força da senha é muito fraca. Configure-a novamente.",	
	s0652sftp:    "Senha inválida.",
	s0653sftp:    "O limite para o período máximo ocioso é de [60 300].",
	s0654sftp:    "Ativar",
	s0655sftp:    "Desativar",
	s0656sftp:    "Somente leitura",
	s0657sftp:    "Leitura e gravação",
	s0658sftp:    "Diretório inválido",

	ftp001:			'Pode partilhar o conteúdo de equipamentos USB conectados à rede usando o protocolo FTP.',
	ftp002:			'Lembre-se que este serviço está desativado por default. Recomendamos que, por motivos de segurança, desative esses serviços quando não os usar',
	ftp003:			'ADATA USB Flash Drive',
	ftp004:			'Nome de utilizador',
	ftp005:			'Password atual',
	ftp006:			'Endereço FTP',
	ftp007:			'Compartilhe pela Internet',
	ftp008:			'Compartilhe pela Internet',
    ftp009:			'Partilhe todas as pastas',
	ftp010:			'FTP Port',
	ftp011:			'Quando ativa a partilha pela Internet, uma ligação FTPS segura é sempre usada. Pode ver os seus certificados RootCA e Webserver na página Certificados no menu Configurações.',
	ftp012:			'Diretório especificado:',
    ftp013:         'Por motivos de segurança, o SFTP no lado da WAN é automaticamente desativado no espaço de 24 horas ou após o reinício.'
};

var usb_ptvdf={
	usb001:			'O router permite que equipamentos USB, como unidades USB, discos rígidos, modems ou impressoras 3G, sejam partilhados pela rede ou pela Internet. Os equipamentos de armazenamento em massa são suportados com os seguintes sistemas de arquivos: FAT16, FAT32 e NTFS.',
	usb002:			'Abaixo poderá encontrar um resumo dos equipamentos USB atualmente conectados.',
	usb003:			'Equipamentos USB ligados',
	usb004:			'No USB Devices',
} 
﻿var LogviewLgeDes =
{
	s0100:    "Nesta página, é possível configurar, transferir e consultar registos do utilizador.",
	s0100a:   "Nesta página, é possível transferir e consultar registos do utilizador.",
	s0101:    "Registo do Utilizador",
	s1613:    "View Logs",
	s1614:    "You can view log information in the box below.",
	s0b01:    "Ativar  Filtro e Definir Nível de Filtro",
	s0b02:    "Nesta página, pode especificar o nível de registo e se pretende guardá-los (registos e níveis alto serão guardados).",
	s0b03:    "Guardar registo:",
	s0b04:    "Nível de registo:",
	s0b05:    "Fatal",
	s0b06:    "Crítico",
	s0b07:    "Importante",
	s0b08:    "Erro",
	s0b09:    "Atenção",
	s0b0a:    "Aviso",
	s0b0b:    "Informação",
	s0b0c:    "Depurar",
	s0b0d:    "Aplicar",
	s0b0e:    "Cancelar",
	s0b0f:    "Transferir e Ver registos",
	s0b10:    "Pode ver e transferir ficheiros de registos.",
	s0b11:    "Transferir ficheiro de registo",
	s0b12:    "Ativar  guardar registo",
	s0b13:    "Nesta página, pode especificar se pretende guardar registos.",
	s0b14:    "Tipo de registo:",
	s0b15:    "Configuração de registo",
	s0b16:    "Registo shell",
	s0b17:    "Registo de alarme",
	s0b18:    "Todos os registos"
};
 
