var framedesinfo =
{
	frame001: 		"ユーザー名 :&nbsp;",
	frame002: 		"パスワード :&nbsp;",
	frame003: 		"ログイン",
	frame004SONET: 	"ONUのウェブページ - ネットワーク設定",
	frame006: 		"IE6.0以下のバージョンはサポートできません。",
	frame007: 		"アカウントは必須項目です。",
	frame008: 		"アカウントが無効です。",
	frame009: 		"パスワードは必須項目です。",
	frame010: 		"パスワードが無効です。",
	frame011: 		"再試行回数が多すぎます。 ",
	frame012: 		"秒後に再試行してください。",
	frame012a: 		"秒後に再試行してください。",
	frame013: 		"再試行回数が多すぎます。",
	frame013a:		"再試行回数が多すぎます。",
	frame014: 		"アカウントとパスワードの組み合わせが不正確です。 もう一度やり直してください。",
	frame015: 		'Copyright © Huawei Technologies Co., Ltd. 2022. All rights reserved.',
	frame015a: 		'Copyright © 2022 Huawei Technologies Co., Ltd. All rights reserved.',
	frame016: 		'ブラウザのバージョンが古いです(IE 6、IE 7、IE 8はサポートされていません)。ブラウザをIE 9以上に更新する必要があります。',	

	mainpage001:	"ネットワーク接続状態:",
	mainpage002:	"正常",
	mainpage003:	"ネットワーク状態が異常です。",
	mainpage004:	"ワンクリック診断",
	mainpage005:	"インターネット",
	mainpage006:	"Wi-Fi設定",
	mainpage007:	"スキャンする",
	mainpage008:	"高速設定",
	mainpage009:	"ログアウト",
	mainpage010:	"Wi-Fiデバイス",
	mainpage011:	"有線デバイス",
	mainpage012:	"電話",
	mainpage013:	"アプリのダウンロード",
	mainpage014:	"ワンクリック診断",
	mainpage015:	"RESET",
	mainpage016:	"備考: 別のページに切り替えると、アップグレードが中断され、次回デバイスがうまく起動できない可能性があります。 キャンセルを選択し、アップグレードが完了するまでこのページを切り替えないことをお薦めします。",
	mainpage017:	"このシステムでは、ワンクリック診断を実行中です。このページを閉じると、診断が停止されます。このページを閉じますか？",
	mainpage018:    "LAN Devices"
};
