var framedesinfo =
{
	frame001:		"Kullanıcı Adı :&nbsp;",
	frame002:		"Şifre :&nbsp;",
	frame003:		"Giriş Yap",
	frame004:		"Huawei ağ yapılandırması web sayfasına hoş geldiniz.",
	frame004telmex:		"Huawei ağ yapılandırması web sayfasına hoş geldiniz.",
	frame004lan:		"Huawei ağ yapılandırması web sayfasına hoş geldiniz.",
	frame005lan:		"Welcome to use the Huawei terminal, making you easy complete network settings.",
	frame004SONET:	"Welcome to web page for network configuration.",
	frame004SINGTEL:"Welcome to Singtel Optical Network Router!",
	frame004SINGTELHS:"Welcome to Optical Network Router!",
	frame006:		"6.0'dan düşük IE sürümü desteklemiyoruz.",
	frame007:		"Kullanıcı Adı alanı gerekli.",
	frame008:		"Kull. Adı geçersiz.",
	frame009:		"Şifre alanı gerekli.",
	frame010:		"Şifre geçersiz.",
	frame011:		"Fazla deneme, lütfen ",
	frame011TALKTALK:"Too many retrials, Please check the Caps state, and retry ",
	frame011a:		"Too many retries, please retry in ",
	frame012:		" sn bekleyin.",
	frame012a:		" second later.",
	frame012c:		" second.",
	frame012d:		" seconds.",
	frame013: 		"Fazla deneme.",
	frame013a:		"Fazla deneme.",
	frame013b:		"Şifre değiştirilmeden uzaktan erişim açılamaz.",
	frame014: 		"Yanlış Kullanıcı Adı/Şifre ikilisi. Lütfen tekrar deneyin.",
	frame014TALKTALK:"Incorrect User Name/Password combination. Please check the Caps state, and try again.",
	frame015: 		'Telif Hakkı © Huawei Technologies Co., Ltd. 2022. Tüm hakları saklı.',
	frame015a: 		'Telif Hakkı © 2022 Huawei Technologies Co., Ltd. Tüm hakları saklı.',
	frame016: 		'Kullanıcı adı ve şifre nasıl alınır?',
	frame0161: 		'Kullanıcı adı ve şifre nasıl alınır?',	
	frame017: 		'Varsayılan giriş şifrenizi bulun',
	frame018: 		'Varsayılan şifreyi ürün isim etiketinde bulabilirsiniz.',
	frame019: 		'Şifreyi unuttunuz mu?',
	frame020: 		'Vars. giriş şifresini geri yükle',
	frame021: 		'Giriş şifresini değiştirip unuttuysanız varsayılan giriş şifresinin kullanılabilmesi için \'Sıfırla\' düğmesine 10 saniye boyunca basarak fabrika ayarlarını geri yükleyebilirsiniz. Varsayılan giriş şifresi ürün adı etiketinde bulunabilir.',	
	frame022: 		'Not: Cihaz fabrika varsayılan ayarlarına geri yüklendikten sonra yapılan tüm ayarlar kaybolur.',
	
	mainpage001:	"Ağ bağlantısı durumu:",
	mainpage002:	"normal",
	mainpage003:	"Ağ durumu normal değil.",
	mainpage003a:	"The network status is unavailable.",
	mainpage004:	"Tek Tuşla Tanılama",
	mainpage005:	"İnternet",
	mainpage006:	"Wi-Fi yapılandırması",
	mainpage007:	"Tara",
	mainpage008:	"Hızlı Ayarlama",
	mainpage009:	"Çıkış yap",
	mainpage010:	"Wi-Fi cihazları",
	mainpage011:	"Kablolu cihazlar",
	mainpage037:	"Wi-Fi cihazları",
	mainpage038:	"Kablolu cihazlar",
	mainpage019:    "Mode Switching",
	mainpage020:    "Router",
	mainpage021:    "Access Point",
	mainpage022:    "Range Extender",
	mainpage043:    "Autonegotiation",
	mainpage044:    "Automatic detection determines whether the gateway works in router mode or bridge mode.",
	mainpage025:    "Transforms your existing wired network to a wireless network.",
	mainpage026:    "Extends your existing wireless coverage by repeating the wireless signal.",
	mainpage027:    "The device operates as a LAN upstream gateway in the routing mode.",
	mainpage028:    "The switched mode takes effect after you restart the device.",
	mainpage023:    "Cancel",
	mainpage033:    "Skip",
	mainpage024:    "Save",
	mainpage029:    "gateway",
	mainpage030:    "Access Point",
	mainpage031:    "2.4GHz",
	mainpage039:    "g.hn",
	mainpage040:    "The system is restarting，please waiting...",
	mainpage041:    "Bridge",
	mainpage042:    "Depending on the gateway connection, determine whether the current mode is the access point or the repeater.",	
	mainpage036:    "Exit",
	mainpage035:    "Range Extender",
	mainpage034:    "Router",
	mainpage032:    "5GHz",
	mainpage012:	"Telefonlar",
	mainpage013:	"APP İndir",
	mainpage014:	"Tanılama",
	mainpage015:	"SIFIRLA",
	mainpage016:	"Not: Yükseltme yarıda kesilir ve başka bir sayfaya geçerseniz cihaz bir dahaki sefere başarılı bir şekilde başlatılamayabilir. Yükseltme işlemi tamamlanana kadar iptal düğmesine basmanız ve bu sayfada kalmanız önemle tavsiye edilir.",
	mainpage017:	"Not: Sistem tek tıklamayla tanılama gerçekleştiriyor Bu sayfadan çıkmak tanıyı durduracak Bu sayfadan çıkmak istediğinizden emin misiniz?",
	mainpage018:    "LAN Cihazlar"
};
