var framedesinfo =
{
	frame001:		"User Name :&nbsp;",
	frame002:		"Password :&nbsp;",
	frame003:		"Log In",
	frame004:		"Welcome to Huawei web page for network configuration.",
	frame004SONET:	"Welcome to web page for network configuration.",
	frame004SINGTEL:"Welcome to Singtel Optical Network Router!",
	frame006:		"We cannot support the IE version which is lower than 6.0.",
	frame007:		"Account is a required field.",
	frame008:		"Account is invalid.",
	frame009:		"Password is a required field.",
	frame010:		"Password is invalid.",
	frame011:		"Too many retrials, please retry ",
	frame012:		" seconds later.",
	frame012a:		" second later.",
	frame013: 		"Too many retrials.",
	frame013a:		"Too many retrials.",
	frame014: 		"Incorrect account/password combination. Please try again.",
	frame015: 		'Copyright © 2022 Huawei Technologies Co., Ltd. All rights reserved.',

	mainpage001:	"Network connection status:",
	mainpage002:	"normal",
	mainpage003:	"The network status is abnormal.",
	mainpage004:	"One-Click Diagnosis",
	mainpage005:	"Internet",
	mainpage006:	"Wi-Fi configuration",
	mainpage007:	"Scan it",
	mainpage008:	"Fast Setting",
	mainpage009:	"Logout",
	mainpage010:	"Wi-Fi devices",
	mainpage011:	"Wired devices",
	mainpage012:	"Phones",
	mainpage013:	"Download APP",
	mainpage014:	"Diagnosis",
	mainpage015:	"RESET",
	mainpage016:	"Note: Upgrade will be interrupted and the device might not boot successfully next time if you switch to another page. It is strongly recommended to press cancel and remain on this page until the upgrade is complete.",
	mainpage017:	"Note: The system is performing one-click diagnosis. Quitting this page will stop the diagnosis. Are you sure you want to quit this page?"
};
