var framedesinfo =
{
	frame001:		"Nome do usuário :&nbsp;",
	frame002:		"Senha :&nbsp;",
	frame003:		"Entrar",
	frame004:		"Bem-vindo à página da web da Huawei para configuração de rede.",
	frame006:		"Não podemos suportar a versão do IE que é inferior a 6.0.",
	frame007:		"O nome de usuário é um campo obrigatório.",
	frame008:		"O nome de usuário é inválido.",
	frame009:		"A senha é um campo obrigatório.",
	frame010:		"A senha é inválida.",
	frame011:		"Demasiadas tentativas, tente novamente ",
	frame012:		" segundos depois.",
	frame013: 		"Demasiadas tentativas.",
	frame014: 		"Combinação incorreta de nome de usuário/senha. Tente novamente.",
	frame015: 		'Copyright © Huawei Technologies Co., Ltd. 2022. Todos os direitos reservados.',
	frame015a: 		'Copyright © 2022 Huawei Technologies Co., Ltd. Todos os direitos reservados.',
	frame016: 		'Como obter seu nome de usuário e senha?',	
	frame017: 		'Procure sua senha de login predefinida.',
	frame018: 		'Pode encontrar a senha predefinida na placa de identificação do produto.',
	frame019: 		'Esqueceu a senha?',
	frame020: 		'Restaurar senha de logon padrão',
	frame021: 		'Se modificou a senha de login e a esqueceu, pode pressionar o botão \'Reset\' por 10 segundos para restaurar as configurações da fábrica, para que a senha de login predefinida possa ser usada. A senha de login predefinida pode ser encontrada na placa de identificação do produto.',	
	frame022: 		'Nota: Todas as configurações feitas serão perdidas depois que restaurar o dispositivo aos padrões de fábrica.',
    frameValidate: 	"Validar o código :&nbsp;",
    frameValidate1: 	"Senha predefinida :&nbsp;",
	
	mainpage001:	"Estado de conexão da rede:",
	mainpage002:	"normal",
	mainpage003:	"O estado da rede é anormal.",
	mainpage004:	"Diagnóstico a um clique",
	mainpage005:	"Internet",
	mainpage006:	"Configuração de Wi-Fi",
	mainpage007:	"Escaneia-o",
	mainpage008:	"Configuração rápida",
	mainpage009:	"Sair",
	mainpage010:	"Dispositivos de Wi-Fi",
	mainpage011:	"Dispositivos com fio",
	mainpage037:	"Dispositivos de Wi-Fi",
	mainpage038:	"Dispositivos com fio",
	mainpage019:    "Modo de alteração",
	mainpage020:    "Roteador",
	mainpage021:    "Ponto de acesso",
	mainpage022:    "Extensor de alcance",
	mainpage043:    "Autonegociação",
	mainpage044:    "A detecção automática determina se a gateway funciona no modo de roteador ou no modo de ponte.",
	mainpage025:    "Transforma sua rede com fio existente em uma rede sem fio.",
	mainpage026:    "Estende a cobertura sem fio existente pela repetição do sinal sem fio.",
	mainpage027:    "O dispositivo funciona como um gateway da LAN a montante no modo de roteamento.",
	mainpage028:    "O modo alterado tem efeito após o reinício do dispositivo.",
	mainpage023:    "Cancelar",
	mainpage033:    "Saltar",
	mainpage024:    "Salvar",
	mainpage029:    "gateway",
	mainpage030:    "Ponto de acesso",
	mainpage031:    "2.4GHz",
	mainpage039:    "g.hn",
	mainpage040:    "O sistema está reiniciando, aguarde...",
	mainpage041:    "Ponte",
	mainpage042:    "Dependendo da conexão de gateway, determine se o modo atual é o ponto de acesso ou o repetidor.",	
	mainpage036:    "Sair",
	mainpage035:    "Extensor de alcance",
	mainpage034:    "Roteador",
	mainpage032:    "5GHz",
	mainpage012:	"Telefones",
	mainpage013:	"Fazer o download do APP",
	mainpage014:	"Diagnóstico",
	mainpage015:	"REDEFINIR",
	mainpage016:	"Nota: A atualização será interrompida e talvez o dispositivo não inicialize com sucesso na próxima vez se alternar para outra página. Recomenda-se fortemente que pressiona cancelar e permanece nesta página até que a atualização está completa.",
	mainpage017:	"Nota: O sistema está efetuando o diagnóstico de um clique. Sair desta página vai interromper o diagnóstico. Tem certeza que quer sair desta página?",
	mainpage018:    "Dispositivos LAN",
	mainpage045:    "Bem-vindo a usar Huawei",
	mainpage046:    "Roteador",
	mainpage047:    "Aqui está um início rápido após o seu primeiro login...",
	mainpage048:    "Tente agora",
	mainpage050:    "Não configurado"
};